compucorp/uk.co.compucorp.civiawards

- .gitignore
- LICENSE.txt
- README.md
- bin/install-php-linter
- civiawards.civix.php
- civiawards.php
- info.xml
- package-lock.json
- package.json
- phpcs-ruleset.xml
This PR adds the CIviAwards Extension.
The basic  core Extension files were added. The extension was added with the uk.co.compucorp.civicase extension as a dependency. Also PHP linter was added.
> RSE-291: Add CiviAwards Extension

- info.xml
> RSE-292:Test auto deployment.

- info.xml
> RSE-292: Test auto deployment2

- CRM/CiviAwards/Helper/CaseTypeCategory.php
- CRM/CiviAwards/Setup/AddAwardsCgExtendsOptionValue.php
- CRM/CiviAwards/Setup/CreateAwardsCaseCategoryOption.php
- CRM/CiviAwards/Setup/DeleteAwardsCaseCategoryOption.php
- CRM/CiviAwards/Setup/DeleteAwardsCgExtendsOption.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Base.php
- info.xml
As we are moving to a new workflow, where the `award-develop` branch wont exist anymore. So merging from `award-develop` to `master`, before getting rid of `award-develop` branch.
> RSE-439: Merge to Develop

- .eslintrc.json
- ang/civiawards.ang.php
- ang/civiawards.css
- ang/civiawards.js
- ang/civiawards/app.routes.js
- ang/civiawards/awards/AwardsNew.html
- ang/civiawards/awards/AwardsNew.js
- civiawards.php
- package-lock.json
- package.json
As part of this PR, a new Angular JS page has been created for Creating New Awards.
1. JS linters has been set up.
2. New angularjs module `civiawards` has been set up.
> RSE-345: Create new Angular Page for creating new award

- CRM/CiviAwards/Api/Wrapper/AwardDetailExtraFields.php
- CRM/CiviAwards/BAO/AwardDetail.php
- CRM/CiviAwards/Service/AwardDetail.php
- CRM/CiviAwards/Service/AwardProfile.php
- api/v3/AwardDetail.php
Award review fields are basically custom fields from the Applicant review custom group. This PR adds the functionality to save, retrieve and delete these fields using the already available AwardDetail API  create in #11 .
CRUD functionality for Award Review fields does not exist.
The award review fields can be passed in via the review fields parameter when creating an award detail.
```php
$result = civicrm_api3('AwardDetail', 'create', [
'award_manager' => [202, 203],
'case_type_id' => 3,
'start_date' => "2019-06-01",
'end_date' => "2019-06-02",
'award_type' => "1",
'review_fields' => [2,3,4]
]);
```
Deleting an AwardDetail will delete the review fields also
```php
$result = civicrm_api3('AwardDetail', 'delete', [
'id' => 4],
]);
```
- Review fields for an award are basically activity …
> RSE-452: Implement CRUD functionality for Award Review fields

- CRM/CiviAwards/Setup/CreateApplicantReviewActivityType.php
- CRM/CiviAwards/Setup/DeleteApplicantReviewCustomField.php
- CRM/CiviAwards/Upgrader.php
- xml/custom_fields/applicant_review_install.xml
This PR merges the work done in https://github.com/compucorp/uk.co.compucorp.civiawards/pull/8 to the Awards Epic branch.
> RSE-349: Install "Applicant Review" Activity type and custom field set

- civiawards.php
This PR merges in the work done in https://github.com/compucorp/uk.co.compucorp.civiawards/pull/7 to the Awards Epic branch.
> RSE-299: Create Awards Permissions

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
When "My Awards" filter was applied, Activities and Cases from other cases was visible in Dashboard.
This is related to https://github.com/compucorp/uk.co.compucorp.civicase/pull/342
Check https://github.com/compucorp/uk.co.compucorp.civicase/pull/342.
In `/more-filters-dashboard-action-button.controller.js`
1. The `AwardDetail.get` API returns an error, if an empty array is passed to the `case_type_id: {IN: <array>}` parameter. To fix this, this following logic is implemented
```javascript
if (caseTypeIDs.length === 0) {
return $q.resolve([]);
} else {
filters.case_type_id = { IN: caseTypeIDs };
}
```
2. Similar fixes are done when broadcasting the `civicase::dashboard-filters::updated` event.
```javascript
var caseTypeFilter = awardTypeIds.length > 0
? { IN: awardTypeIds }
: ''; …
```
> RSE-363: "My Awards" filter bug fixes

- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.html
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/mocks/data/review-panels.data.js
As Part of this PR, the Application Status and Anonymize Application support to the Add/Edit Review Panel popup has been added.
1. In `review-panel-popup.html`, markup for the Tabs inside Review Panel popup has been added.
2. In `review-panels.directive.js` functions has been added to handle the above features.
> RSE-674: Add tabs and Application Status to Review Panel

- README.md
As part of this PR, the Readme file of the extension has been updated to reflect the minimum version of CiviCase.
> RSE-1051: Update Readme

- README.md
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- info.xml
**New Features:**
- Creating/Editing/Viewing An Award
- Administering Award Scoring Fields
- Submitting/Editing/Viewing An Applicant Review
- Awards Dashboard.
- Awards Permissions.
- Awards Application Custom Fields.
- Award Review Panels Functionality.
> RSE-1051: Release v1.0.0-beta.1

- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/mocks/data/review-panels.data.js
As part of this PR, the Panel Application Status Restriction UI and Functionality has been added.
1. Added markup in `review-panel-popup.html`.
2. Save and fetch logic is added to `review-panels.directive.js`.
3. Also `formatReviewPanelDataForUI` was too big to manager, broke it down into 2 functions, `formatContactSettings` and `formattedVisibilitySettings`.
> ACU-68: Panel Application Status Restriction UI + Functionality

- CRM/CiviAwards/BAO/AwardReviewPanel.php
- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/mocks/data/review-panels.data.js
- tests/phpunit/CRM/CiviAwards/BAO/AwardReviewPanelTest.php
This PR contains work done for the following PRs
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/88
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/90
> ACU-32: Application Restricted Status

- ang/civiawards/reviews-tab/services/reviews-case-tab-content.html
- ang/civiawards/reviews-tab/services/reviews-case-tab.service.js
This PR is related to https://github.com/compucorp/uk.co.compucorp.civicase/pull/463
Similar to that PR, the placeholder for Review Tab has been moved to the content file.
> CATL-1358: Move review tab placeholders

- info.xml
**Improvements**
- In Case Details Reviews tab, width of Text Fields, Text Area and Rich Text Editor has been fixed, to avoid too long strings to be displayed.
**Bug Fixes**
- Fixed a bug with AwardReviewPanel API, where review panel details where returned, even when the sent Contact ID is not in any review panel.
**Updates for Developers**
- Added Github Action to run Javascript Unit Tests.
- Code improvements has been made to the review tab placeholder.
> RSE-1121: Release v1.0.0-beta.3

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
- xml/Menu/civiawards.xml
These PR contains a list of changes made for the Award review form so that it can be used in SSP as well as in Civicrm. 
The changes are detailed in the following PR's
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/100
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/105
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/98
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/109
> RSE-44: Award Review Form Changes

- ang/civiawards/award-creation/directives/basic-details-form.directive.js
- ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.js
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/civiawards/shared/directives/contacts-group-dropdown.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/mocks/data/review-panels.data.js
This PR is related to https://github.com/compucorp/uk.co.compucorp.civicase/pull/511.
`isTruthy` has been used in this PR.
> CATL-1485: Use isTruthy function

- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR updates submit action label on SSP Awards submit review application page from "Submit Application" to "Submit Review"
> DRU-171: Update submit button label on awards review page to Submit Review

- CRM/CiviAwards/Form/AwardCustomField.php
- CRM/CiviAwards/Helper/CaseTypeCategory.php
- CRM/CiviAwards/Service/ApplicantManagementUtils.php
- CRM/CiviAwards/Setup/AddApplicantManagementCaseTypeCustomGroupSupport.php
- CRM/CiviAwards/Setup/CreateAwardTypeOptionGroup.php
- CRM/CiviAwards/Test/Fabricator/CaseCategory.php
This PR fixes PHP linter errors for the Awards instance build branch.
> RSE-1118: Fix PHP Linter errors

- info.xml
**New Features**
* Users can now create case categories for applicant management instance. [RSE-1118](https://github.com/compucorp/uk.co.compucorp.civiawards/pull/122).
**Improvements**
* Tag colours were added to award review form header. [RSE-841](https://github.com/compucorp/uk.co.compucorp.civiawards/pull/101).
* Done button was added to the review fields popup. [RSE-982](https://github.com/compucorp/uk.co.compucorp.civiawards/pull/108).
* In permissions tab statuses dropdown is only visible once "Panel can change the status of an application?" check box is ticked. [RSE-1141](https://github.com/compucorp/uk.co.compucorp.civiawards/pull/102).
* Text on Review submitted modal is changed. [RSE-1219](https://github.com/compucorp/uk.co.compucorp.civiawards/pull/114).
* All review fields …
> CPS-335: Release v1.0.0-beta.4

- info.xml
**New Features**
* RSE-44: Award Custom Group By SubTypes and Manage Workflow Functionality #143
**Bug Fixes**
* CPS-360: Fix save award bug when there are no custom fields defined #138
> CPS-375: Release v1.0.0-beta.6

- CRM/CiviAwards/Helper/CustomGroupPostProcess.php
- CRM/CiviAwards/Service/ApplicantManagementCustomGroupDisplayFormatter.php
- tests/phpunit/CRM/CiviAwards/Service/ApplicantManagementAwardDetailPostProcessorTest.php
- tests/phpunit/CRM/CiviAwards/Service/ApplicantManagementCustomGroupDisplayFormatterTest.php
- tests/phpunit/CRM/CiviAwards/Service/ApplicantManagementCustomGroupPostProcessorTest.php
This pr adds tests for classes that are responsible for applicant management custom group post processing.
This pr adds tests for following classes
- CRM_CiviAwards_Service_ApplicantManagementAwardDetailPostProcessor.
- CRM_CiviAwards_Service_ApplicantManagementCustomGroupPostProcessor.
- CRM_CiviAwards_Service_ApplicantManagementCustomGroupDisplayFormatter.
> RSE-1448: Unit Tests For Applicant Management Post Processing Classes

- info.xml
- Added is_template field to AwardDetails https://github.com/compucorp/uk.co.compucorp.civiawards/pull/154
- Fixed markup of 'Review Submitted' button https://github.com/compucorp/uk.co.compucorp.civiawards/pull/148
- When creating a review panel, only statuses associated with award type is displayed
- Fixed Contact Group limit on review panels https://github.com/compucorp/uk.co.compucorp.civiawards/pull/151
> CPS-397: Release 1.0.0-beta.8

- ang/civiawards-workflow/action-links/controllers/workflow-advanced.controller.js
- ang/civiawards-workflow/action-links/directives/workflow-list-advanced-action.html
- ang/civiawards-workflow/configs/application-management-workflow-list-action-items.config.js
- ang/test/civiawards-workflow/action-links/controlers/workflow-advanced.controller.spec.js
As part of this PR, a new dropdown "Advanced" has been added to the Workflow list page. When clicked on this dropdown item, it redirects to the Core Case Type Edit screen for the clicked workflow.
1. Added the new Dropdown via `application-management-workflow-list-action-items.config.js`.
2. Also added `action-links/directives/workflow-list-advanced-action.html` and `action-links/controllers/workflow-advanced.controller.js` to implement the feature itself.
> RSE-1600: Implement "Advanced" Action Dropdown

- info.xml
- Addition of new columns and filters to the workflow list page #156
- Add a button for creating a new workflow  #159
- Applicant Management edit workflow link #160
- Add Option Limit Parameter To Award Manager Get Api Call #162
- Fix Bug In Review Field Reordering #166
- Fix Custom Fields Issue On Awards #165
- Fix failing Drupal Build For Unit Test Workflow #158
> CPS-438: Release v1.0.0-beta.9

- info.xml
* RSE-1600: Implement "Advanced" Action Dropdown #167 
* RSE-881: Show disabled applications #173
* CPS-411: Import awards using CSV importer extension #164
* CPS-423: Sync Log Tables With Actual Tables While Running Upgraders #176
> CPS-449: Release v1.0.0-beta.10

- info.xml
* RSE-1620: Fix Award Custom Fields Leakage Bug #174
* RSE-1295: Fix Create/Edit Award Redirection #180
> CPS-466: Release v1.0.0-beta.11

- info.xml
- Sync Log Tables In Base Upgrader #187
- Awards Payments Management #191
- Add Pagination to Manage Workflow and Dashboard Page + New Apis #177
> CPS-471: Release v1.0.0-beta.12

- CRM/CiviAwards/Form/AwardReview.php
Recently on a client site, intermittently, review fields would be unavailable when a reviewer tries to add a review. Clearing the cache would fix the issue but issue would re-appear again after some time.
The review fields appear and does not disappear intermitently
The function we are using to fetch profile fields for the Awards Review Form: `CRM_Core_BAO_UFGroup::getFields` sets profile custom fields in the cache [here](https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/BAO/UFGroup.php#L729) so that next time the function fetches custom fields for a profile, the values are returned from the cache. 
The issue is that the function is used in a lot of places in core and the cache value can easily be overwritten because none of those places passes the `$ctype` variable which …
> ACU-548: Fix Issue with Disappearing Review Fields

- CRM/CiviAwards/Service/ApplicantManagementMenu.php
This PR changes the sub-item "Menu awards" to "Menu Awards".
Changes implemented along with PR https://github.com/compucorp/uk.co.compucorp.civicase/pull/743
> CPS-487: Capitalize Category Name on Label Menu

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR adds status on View Review screen.
The field did not exist.
> RSE-1774: Show status on view screen

- CRM/CiviAwards/BAO/AwardReviewPanel.php
- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/mocks/data/review-panels.data.js
- templates/CRM/CiviAwards/Form/Award.hlp
In this PR we add a new form field to the award review panel,  this field allows the award manager to specify case roles that can review an award application.
Award managers are not able to specify case roles that will be able to review an award application.
Award managers are able to specify case roles that will be able to review applications within the self-service portal “review applications screen”.
For the help icon to work, the `crmUiHelp()` has to be bind to the current scope object, but the review-panel dialog box is in a different new scope created by the dialog service, which cannot be modified outside the service.
https://github.com/totten/angular-jquery-dialog-service/blob/bf99b23160e8e3090bc1e03fbddd1688ecd24923/dialog-service.js#L40-L41
To workaround this, I bind the …
> RSE-1760: Allow managers to specify case roles that can review an application

- CRM/CiviAwards/BAO/AwardReviewPanel.php
- CRM/CiviAwards/Form/AwardReview.php
- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- CRM/CiviAwards/Service/AwardPanelContact.php
- CRM/CiviAwards/Setup/CreateApplicationReviewerRelationship.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1012.php
- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
- ang/test/mocks/data/award.data.js
- ang/test/mocks/data/review-panels.data.js
- ang/test/mocks/data/reviews.data.js
- api/v3/AwardReviewPanel.php
- bin/install-php-linter
- templates/CRM/CiviAwards/Form/Award.hlp
- templates/CRM/CiviAwards/Form/AwardReview.tpl
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
- tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
This PR merges workstream branch to master branch.
> RSE-1743:  Merge work stream to master

- .github/workflows/unit-test.yml
- CRM/CiviAwards/Form/AwardPayment.php
- CRM/CiviAwards/Service/AwardCaseFilterPreProcess.php
- CRM/CiviAwards/Test/Fabricator/CaseCategory.php
- CRM/CiviAwards/Upgrader.php
- tests/phpunit/BaseHeadlessTest.php
- tests/phpunit/CRM/CiviAwards/Form/AwardPaymentTest.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
Merge the PHP8 and CiviCRM 5.51.3 PR fixes into the master branch.
The PR(s):
- https://github.com/compucorp/uk.co.compucorp.civiawards/pull/263
- https://github.com/compucorp/uk.co.compucorp.civiawards/pull/262
- https://github.com/compucorp/uk.co.compucorp.civiawards/pull/261
> CIVIIB-57: Merge the PHP8 PR fixes into the master branch

- info.xml
> COMCL-362: Bump version to 2.1.4

- info.xml
> COMCL-921: Merge Rc Branch To Master

- info.xml
> COMCL-981: Merge Rc Branch To Master

- CRM/CiviAwards/Settings.php
- ang/civiawards-base.ang.php
- ang/civiawards-payments-tab.ang.php
- info.xml
This PR bumps version to 2.4.0
> COMCL-1012: Bump Version
