compucorp/uk.co.compucorp.civiawards

- CRM/CiviAwards/Setup/CreateAwardsCaseCategoryOption.php
- CRM/CiviAwards/Setup/DeleteAwardsCaseCategoryOption.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Base.php
This PR adds the Awards case type category when the `uk.co.compucorp.civiawards` is installed. 
The Awards case type category is not present.
- The Awards case type category is added when the `uk.co.compucorp.civiawards` is installed and removed when the extension is uninstalled.
- This PR also makes the extension Upgrader functionality to be compatible the compucorp’s recommended way.
> RSE-296:  Create Award Case Type Category

- CRM/CiviAwards/Helper/CaseTypeCategory.php
- CRM/CiviAwards/Setup/AddAwardsCgExtendsOptionValue.php
- CRM/CiviAwards/Setup/CreateAwardsCaseCategoryOption.php
- CRM/CiviAwards/Setup/DeleteAwardsCgExtendsOption.php
- CRM/CiviAwards/Upgrader.php
This PR adds the Awards Case type category to the Core `cg_extend_objects` option group. This will enable us to add custom fields that extend case types for this category.
This functionality was not present.
- Custom groups can now be added for the Award Case type category.
> RSE-297: Add the Awards Category to the CG extends Option Group

- CRM/CiviAwards/Setup/CreateAwardTypeOptionGroup.php
- CRM/CiviAwards/Upgrader.php
This PR adds the Award Type option group with default option values.
This option group does not exist.
The option group is created
> RSE-492: Create award type option group.

- CRM/CiviAwards/Setup/AddAwardsCategoryWordReplacement.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/WordReplacement/AwardsCategory.php
- config/word_replacement/awards_category.php
We need to add the word replacement config file for awards so that on dashboard and manage cases page word replacements are done.
Function did not exists before
Implemented a class `CRM_CiviAwards_WordReplacement_AwardsCategory` that implements the CRM_Civicase_WordReplacement_BaseInterface and provides a method that returns the word replacements array.
```php
return [
'Case' => 'Award',
'Cases' => 'Awards',
'case' => 'award',
'cases' => 'awards',
];
```
This `CRM_CiviAwards_WordReplacement_AwardsCategory` is added via an option value to the `case_type_category_word_replacement_class` option group so that Civicase knows the class to call for word replacements for prospect category related pages.
> RSE-351: Implement Awards Word Replacement

- CRM/CiviAwards/Upgrader.php
The When installing the CiviAwards extension for a site, after installation, there is a notice that extension updates are available. This should not happen as a fresh install of the extension should set the schema version to the version of the latest upgrader.
This PR is based off from the [PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/293) which describes this problem
> CATL-1172: Fix "Database Upgrades Required" Message

- CRM/CiviAwards/Upgrader.php
The When installing the CiviAwards extension for a site, after installation, there is a notice that extension updates are available. This should not happen as a fresh install of the extension should set the schema version to the version of the latest upgrader.
This PR is based off from the [PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/293) which describes this problem
> CATL-1172: Fix database upgrades required warning message

- CRM/CiviAwards/Setup/AddAwardsCgExtendsOptionValue.php
- CRM/CiviAwards/Upgrader.php
When the extension is disabled and you try to access the url `/civicrm/admin/custom/group?reset=1`, an error is displayed as shown in the screenshot below. This PR fixes that. 
The fatal error is caused by the line `'description' => 'CRM_CiviAwards_Helper_CaseTypeCategory::getAwardCaseTypes;'` in https://github.com/compucorp/uk.co.compucorp.civiawards/blob/e9768872150931263bf1596bf3fa1b68305f8e37/CRM/CiviAwards/Setup/AddAwardsCgExtendsOptionValue.php#L30. When the module is disabled, the module files are not loaded again and when Civi tries to resolve the class  `CRM_CiviAwards_Helper_CaseTypeCategory::getAwardCaseTypes` to get the description of the Option value and fails to find the class (because it is not loaded), it throws the fatal error.
When the extension is disabled, we remove …
> CPS-25: Fix error after disabling extension

- CRM/CiviAwards/Setup/CreateAwardsMenus.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1001.php
This PR adds the Civi Awards menu.
The awards menu does not exist.
Follows the same pattern as https://github.com/compucorp/uk.co.compucorp.civicrm.prospect/pull/19/files but the permissions are specific to CiviAwards thanks to this PR: https://github.com/compucorp/uk.co.compucorp.civicase/pull/247
> RSE-303: Add CiviAwards menu items

- civiawards.php
This PR adds `create/edit` permission for the extension
Permission did not exists
> RSE-657: Add Create Edit Awards Permissions

- CRM/CiviAwards/Setup/CreateApplicantReviewActivityType.php
- xml/custom_fields/applicant_review_install.xml
This PR sets correct activity status ('Completed' and 'Scheduled') options to be used by new activity category "Applicant Review"
Action was not present
I added a method in the upgrader to get the statuses `Completed` and `Scheduled` option values and append the name of the activity category `Applicant Review` to the grouping column.
```php
foreach ($statuses as $status) {
civicrm_api3('OptionValue', 'create', [
'id' => $status['id'],
'grouping' => "{$status['grouping']},Applicant Review",
]);
}
```
I also added a method to undo the action above in the uninstaller.
```php
foreach ($statuses as $status) {
$groupings = explode(',', $status['grouping']);
$index = array_search('Applicant Review', $groupings);
if ($index === FALSE){
continue;
} else {
unset($groupings[$index]);
} …
```
> RSE-631: Sets Activity Status 'Scheduled' and 'Completed' for Applicant Review

- CRM/CiviAwards/BAO/AwardDetail.php
- CRM/CiviAwards/Helper/CreateReviewFieldsValidator.php
- CRM/CiviAwards/Service/AwardProfile.php
- api/v3/AwardDetail.php
At the moment, only the ID of every review field is saved as part of “AwardDetails“ API.
Now we need support to add “weight“, “required“ fields too.
Also there is a bug with existing implementation of “review_fields“. it always returns an extra NULL value. If an award is saved with [“19“, 20”], then the api return [“19”, “20“, ““].
Action was not preset
In the method `createProfileFields` , Instead of expecting just a dimensional array of custom field id, the method now expects a 2-dimensional array in the form `[['id' => 1, 'required' => FALSE, 'weight' => 3]]`. This field will now be used to create the `UFField` entry. 
To show, in the method `getProfileFields` , instead of just iterating over the custom fields and stripping and returning the IDs:
```php
foreach ($result['values'] as …
```
> RSE-372: Save More Information for Each Review Field

- api/v3/AwardManager.php
This PR adds an API file for `AwardManager` entity to enable API calls
API actions does not exist for the `AwardManager` entity
> RSE-668: Enable AwardManager API

- ang/civiawards/award-creation/directives/award.directive.html
- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/award-creation/directives/basic-details-form.directive.html
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
As part of this PR the following bugs are fixed
After 'Save' button is pressed from Edit Award screen, 'Saved' notification was missing.
The notification was not displayed.
In `award.directive.js`, added a new function `saveAwardInBG`, which saves the Award in background and shows a notification when saved.
The Manager selection was missing option to create new contacts on the go.
In `basic-details-form.directive.html`, added `create: true` parameter to the manager selection dropdown, which is responsible for showing the create new contact options.
> RSE-305: Bug Fixes

- CRM/CiviAwards/Form/AwardReview.php
The award review fields are now created with more properties like weight, required.
On the Review form which is basically the profile containing the chosen custom fields for the Award, we need to make sure that the fields are ordered by the weight.
No logic to ensure fields were ordered by their weights
Profile fields are now ordered with `weight`
We just set the default options for `CRM_Core_BAO_UFGroup::getFields()` and set `weight` as the `$orderBy` param which is the 11th parameter
> RSE-681: Order Profile Fields by Weight on Review Form

- CRM/CiviAwards/BAO/AwardReviewPanel.php
- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- CRM/CiviAwards/Service/AwardPanelContact.php
- api/v3/AwardReviewPanel.php
An Award Panel consists of settings that define contacts that has access to an Award application and the access they have to the Award application.
When a panel member logs in to the Self Service Portal, we need a way to determine if he has access to review an Award application and if he has, what kind of access does he have i.e what application statuses can he view? Does he have access to real or anonymised data?
This PR adds an API to get this information.
The AwardReviewPanel.getcontactaccess API does not exist.
The AwardReviewPanel.getcontactaccess is added.
**Sample Request**
```php
$result = civicrm_api3('AwardReviewPanel', 'getcontactaccess', [
'contact_id' => 9,
'award_id' => 2,
]);
```
**Sample Response:**
```php
{
"is_error": 0,
"version": 3,
"count": 3,
"values": { …
```
> RSE-664: Add API to return a Contact's Access to an Award Application

- CRM/CiviAwards/BAO/AwardReviewPanel.php
- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- CRM/CiviAwards/Service/AwardPanelContact.php
- CRM/CiviAwards/Test/Fabricator/AwardReviewPanel.php
- CRM/CiviAwards/Test/Fabricator/CaseType.php
- CRM/CiviAwards/Test/Fabricator/Contact.php
- CRM/CiviAwards/Test/Fabricator/Relationship.php
- CRM/CiviAwards/Test/Fabricator/RelationshipType.php
- api/v3/AwardReviewPanel.php
- phpunit.xml.dist
- tests/phpunit/BaseHeadlessTest.php
- tests/phpunit/CRM/CiviAwards/BAO/AwardReviewPanelTest.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
- tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
- tests/phpunit/bootstrap.php
This PR adds Unit tests for the Award Panel functionality. Also currently there are no PHP unit tests for Back End for the Award extension, so this PR  also does the PHP unit tests setup for the extension.
- There were no tests for the Award Panel functionality
- Tests were added for the Award Panel functionality
> RSE-710: Add Tests For Award Panel Functionality

- civiawards.php
Each case category like Awards, Prospects now have their own respective permissions defined and the permission is needed to access the respective pages for each of the categories.
When testing this functionality, an errors came up for the Award manager when trying to create an Award : API Permission check failed for CaseType/create call: insufficient permission: require Administer Civicase. After fixing this error in https://github.com/compucorp/uk.co.compucorp.civicase/pull/314, an error came up also about permission issue for the AwardDetail entity.
Permission error when Award manager is trying to create an Award
The default permission when an API permission is not defined is `administer Civicrm`, this was the permission set for the AwardDetail API actions and teh Award manager does not …
> RSE-298: Fix Permission Errors

- ang/civiawards/dashboard/configs/awards-dashboard-action-buttons.config.js
- ang/civiawards/dashboard/services/add-award-dashboard-action-button.service.js
- ang/civiawards/shared/configs/case-type-buttons.config.js
- ang/test/civiawards/dashboard/configs/awards-dashboard-action-buttons.config.spec.js
- ang/test/civiawards/dashboard/services/add-award-dashboard-action-button.service.spec.js
- ang/test/civiawards/shared/configs/case-type-buttons.config.spec.js
- ang/test/mocks/configs/awards-case-types.config.js
- ang/test/mocks/data/award.data.js
- ang/test/mocks/modules.mock.js
This PR adds the "Create new award" button to the Awards Dashboard. 
This PR uses https://github.com/compucorp/uk.co.compucorp.civicase/pull/309 in order to add a new action button to the awards dashboard. The configuration options for the button are:
```js
{
buttonClass: 'btn btn-primary civicase__dashboard__action-btn civicase__dashboard__action-btn--white',
iconClass: 'add_circle',
identifier: 'AddAward',
label: 'Create new award',
weight: 100
}
```
The weight is set to `100` so it's displayed after the "Add Case" button.
This button makes reference to the `AddAwardDashboardActionButton` service.
For the visibility method we check that the `case_type_category` URL param is set to `awards`:
```js
function isVisible () {
var urlParams = $location.search();
return …
```
> RSE-366: Add award button

- ang/civiawards/dashboard/services/add-award-dashboard-action-button.service.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/dashboard/configs/awards-dashboard-action-buttons.config.spec.js
- ang/test/civiawards/dashboard/services/add-award-dashboard-action-button.service.spec.js
This PR fixes the "Add Award" button. After creating a new award the new award would not be seen on the dashboard overview section.
The problem happened because we were using the `$location` service to redirect the user the the `awards/new` form. This only changes the hash and does not change the actual page. That means that for the browser, the user was always looking at the dashboard and there was no need to refresh the page.
In turn, not refreshing the page is an issue because the case types (awards in this case) are fetched by PHP when the pages refreshes and are stored in the `CRM['civicase-base'].caseType`  variable.
To force the page to reload we redirect the user to `civicrm/a/#/awards/new` which in turn will redirect to the dashboard by refreshing the page and loading the right …
> RSE-362: Fix Add Award button

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
Previously if the More Filters button is pressed more than once, multiple popups were being created. This PR fixes that.
In `more-filters-dashboard-action-button.controller.js`, added a check to see if the Popup already exists before creating a new one.
> RSE-363: Fix more filters bug

- CRM/CiviAwards/Hook/alterAPIPermissions/Award.php
- civiawards.php
For a user to be able to create and Award, the user must either of `Create / edit award` or `Administer CiviCase`.  Currently when creating an award Case Type, the permission required is the Administer CiviAward  permission. We don't need this permission and it has been removed [here](https://github.com/compucorp/uk.co.compucorp.civicase/pull/326). This PR makes sure that the required permission to create an Award case type is set.
- Currently when creating an award Case Type, the permission required is the Administer CiviAward  permission
-  When creating an award Case Type, the permission required is either `Create / edit award` or `Administer CiviCase`
The `civiawards_civicrm_alterAPIPermissions` hook is used to achieve the functionality. When a call to update/create a Case Type via an …
> RSE-298: Fix Permission Issue with Creating Award for An Award Manager

- ang/civiawards/activity-forms/activity-forms.config.js
- ang/civiawards/activity-forms/services/review-form.service.js
- ang/test/civiawards/activity-forms/activity-forms.config.spec.js
- ang/test/civiawards/activity-forms/services/review-form.service.spec.js
- ang/test/mocks/data/reviews.data.js
This PR displays the review custom form when viewing activities of the review type.
* Uses the activity form provider introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/329
* Adds a `ReviewActivityForm` activity form service that can handle any activity of the `'Applicant Review` type.
> RSE-644: Show reviews form

- ang/civiawards/award-creation/directives/award.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
Previously the People Tab under Case Details was broken for Award Type Cases. This PR fixes that by adding a `Application manager` role for all Awards.
Unlike Case Type of Non Award type, while creating Awards, the `CaseRoles` are not defined, which resulted in the People Tab being broken. To fix this, a role called `Application Manager` is created and the `manager` flag is set to true. Means people assigned to this role, will also be Award Application Manager.
```javascript
definition: {
caseRoles: [{
name: 'Application Manager',
manager: 1
}]
}
```
> RSE-733: Add Application manager role for Awards

- CRM/CiviAwards/Hook/alterAPIPermissions/Award.php
- CRM/CiviAwards/Setup/CreateApplicantReviewActivityType.php
- civiawards.php
Currently when the Award manager is not able to view or add review custom fields to an award except the Award manager has the `administer CiviCRM` and the `access all custom data` permissions. In the real scenario, the Award manager will not have access to these two permissions (at least the `administer CiviCRM` permission). This PR adds a new permission `access review custom field set` that allows the Award manager to view Award review custom fields only (i.e Custom fields belonging to a Custom Group that belongs to the reserved Applicant Review activity type).
Award manager cannot view not add review custom fields without having both the `administer CiviCRM` and the `access all custom data` permissions.
Award manager can view and add review custom fields when assigned the new permission …
> RSE-856: Add Access Review Custom Field Set Permission & Functionality

- CRM/CiviAwards/Hook/alterAPIPermissions/Award.php
Currently an Award manager is able to see other awards belonging to another manager when viewing the dashboard.
Award manager is able to see other awards of which he is not the manager on the dashboard.
Award manager is not able to see other awards of which he is not the manager on the dashboard.
The frontend normally calls the AwardManager.get API to fetch the award types that the current logged in manager has access to. This API call was failing because of permission issues: `insufficient permission, require administer Civicrm`. 
The fix was to set the correct permission for this API so that results are returned and the FE is able to filter award types that the user can see.
> RSE-363: Fix Issue With Awards Showing For User Who is Not Manager

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
As part of this PR, the Award Status filter functionality is fixed.
Previously the Award Status filter was completely missed, that is why it did not work. This is fixed now.
In `more-filters-dashboard-action-button.controller.js` added the `status_id` parameter to the broadcasted object.
```javascript
var param = {
case_type_id: awardTypeIds.length > 0 ? { IN: awardTypeIds } : ''
};
if (model.selectedFilters.statuses.length > 0) {
param.status_id = { IN: getSelect2Value(model.selectedFilters.statuses) };
}
$rootScope.$broadcast('civicase::dashboard-filters::updated', param);
```
> RSE-363: Filter by Award Status

- CRM/CiviAwards/Helper/ApplicantReview.php
- CRM/CiviAwards/Hook/AclGroup/AllowAccessToApplicantReviewGroups.php
- CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
- civiawards.php
Currently for the Award manager to view and save custom field set for an Award, the combination of the `access review custom field set` permission and ACL configuration for the Applicant Review custom group is needed.  We don't need that to happen anymore as we only want the `access review custom field set` permission to be sufficient for the Award manager to view and save applicant review custom field set for an Award.
- For the Award manager to view and save custom field set for an Award, the combination of the `access review custom field set` and ACL configuration for the Applicant Review custom group is needed.
- For the Award manager to view and save custom field set for an Award, only the `access review custom field set` permission is needed.
The `civiawards_civicrm_aclGroup` hook …
> RSE-891:  Allow Award Manger Access Review Custom Field set without ACL configuration

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR allows to modify and view the source contact for a particular review.
We modified the review form class.
* Removed the `getActivityCaseId` function and replaced it with a `getActivity` function. The reason for this was to avoid making multiple calls just to get different fields of the same activity.
* For the default values we use the current logged in user when creating a new review, but the stored source contact when editing the review.
* We tried to replicate the experience from the regular activity form as much as possible hence the field is called "Reported By" when creating or editing the field, but "Added By" when viewing the field.
> RSE-842: Display source contact on review form

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
In Award Dashboard, when Award Status filter is applied, and then removed, it hides all cases/activities. This PR fixes the same.
In https://github.com/compucorp/uk.co.compucorp.civicase/blob/ac67e18c9830754687f0c1ea30561c9fa12ff51a/ang/civicase/dashboard/directives/dashboard.directive.js#L123, the controller listens for `civicase::dashboard-filters::updated`, and adds the sent parameters to `$scope.activityFilters.case_filter` object.
When the status filter is added, `status_id` key gets added, but second time when status filter is removed and as we are using `_.extend`, the `status_id` stays in `$scope.activityFilters.case_filter` object.
To fix this, when status filter is not present, `{ 'IS NOT NULL': 1 }` value is set from `more-filters-dashboard-action-button.controller.js`.
> RSE-952: Show cases/activities when status filter is removed

- ang/civiawards/award-creation/directives/review-fields-table.directive.html
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
Inside the Review tab while creating and award, and also inside the Case Details section, the "Required" column and the Action column was taking more width than its content, this PR fixes the same.
Added static width in the markup.
> RSE-868: Fix Table Column width for review tab

- CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
An Award manager cannot add review panels currently because the default API permission `Administer Civicrm` is required. This PR fixes that and sets appropriate permissions for the AwardReviewPanel API's
- Award Manager cannot create a review panel.
- Award Manager can now create review panels.
The API permissions for AwardReviewPanel Get/Create/Update is set to permissions required for creating an Award.
> RSE-652: Set API Permissions for AwardReviewPanel Entity

- ang/civiawards/dashboard/directives/more-filters-popup.html
- config/word_replacement/awards_category.php
As part of this PR, the word replacement has been set up for CiviAwards.
1. In `awards_category.php`. `Award` has been replaced with `Application`.
2. In `more-filters-popup.html`, `Award Statuses` has been replaced with `Application Statuses`.
> RSE-751: Contact Cases Tab Word Replacement

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
When viewing the Case Dashboard, Case Types were not appearing in Case Overview section. This PR fixes the same.
This bug happened, because the “More Filters” also was working on the background for cases dashboard. In https://github.com/compucorp/uk.co.compucorp.civiawards/blob/4a8c31cba8e4f6839d8fb6c2e9f1862e35fdf7b2/ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.html#L3, as we use `ng-show`, the controller is working on the background. We cant use `ng-if` here, because that way the whole button will stop working, as `isVisible` function is written inside the controller.
So to fix this, in `ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js`, added the following check
```javascript
(function init () {
if (isAwardsScreen()) { …
```
> RSE-967: Do not apply More Filters in non awards dashboard

- ang/civiawards/award-creation/directives/review-panels.directive.js
- ang/civiawards/dashboard/directives/edit-award-button.html
- ang/test/civiawards/award-creation/directives/review-panels.directive.spec.js
The Award edit page has been moved to the new namespace created in https://github.com/compucorp/uk.co.compucorp.civiawards/pull/64. This was missed previously.
The ReviewPanels were always being saved as active, even if the active checkbox is disabled in UI.
Sending `1` or `0` instead of true or false from review-panels.directive.js.
> RSE-777: Fix Misc bugs

- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
This PR fixes the HTML rich text formatting on the reviews tab for awards section.
When adding a review field which contains HTML rich text, the table content doesn't get formatted and show unformatted text for the review pane. See `Before` Screenshot for e.g.
The text was not getting formatted because the HTML was not marked as trusted/safe HTML to be passed through to the browser and angular was not parsing it as an HTML string and passing it as a normal encoded string to the browser.
To fix this, we used `$sce.trustAsHtml` function from the core angular `$sce` service. Using this service while binding HTML in the template fixed the issue.
The solution is being encouraged from [this PR](https://github.com/compucorp/uk.co.compucorp.civicase/pull/345/files)
> RSE-892: Fix HTML text formatting on the review table tab

- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/mocks/data/review-panels.data.js
When there are no defined Specific Relationship in all the Review panels of an award, the Review Panels cannot be seen. This PR fixed that issue.
The `Contact.get` api call is not happening anymore.
In `review-panels.directive.js`, after fetching the Review Panels, we fetch  the list of Contact names from the list of Relationships, but when the relationships are empty, we used to send an empty array to the `Contact.get` api call.
```javascript
return crmApi('Contact', 'get', {
sequential: 1,
return: ['display_name'],
id: { IN: contactIdsToFetch }, // this used to be an empty array
options: { limit: 0 }
})
.then(function (contactsData) {
return contactsData.values;
});
```
So we were getting an `invalid criteria for IN` error.
To fix this, now we check if the list of contacts are empty, …
> RSE-654: Fix error when no Relationships are present in Review Panels

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
This PR is a supportive PR for the changes introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/404. This basically contains the related FE changes done on awards side.
The `getStats` API is improved to support `IS NULL` operator for `case_type_id` parameter. See the technical details of https://github.com/compucorp/uk.co.compucorp.civicase/pull/404.
Related FE changes are being incorporated here
> RSE-944: Fix API param value when case type id is null

- CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
An Award manager cannot delete review panels currently because the default API permission Administer Civicrm is required. This PR fixes that and sets appropriate permissions for deleting review panels.
Award Manager cannot delete a review panel.
Award Manager can now delete a review panel.
> RSE-653: Set Permissions For Deleting Award Panels

- ang/civiawards/activity-forms/services/review-form.service.js
- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
- ang/test/civiawards/activity-forms/services/review-form.service.spec.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
- civiawards.php
This PR adds default activity types to awards so users can use them to create activities related to applications.
**Note:** this PR is linked to https://github.com/compucorp/uk.co.compucorp.civicase/pull/408
The menu does not exist
* We modified the `awards.directive.js` file so it always send the Email, Follow up, Meeting, and Phone Call activities when saving the award (case type) definition. These activities are manually selected because that's how core defines them instead of selecting the communication activity grouping, which includes extra activities.
* The `review-form.service.js` service was refactored so it allows for options overriding so we can display different kind of forms depending on the action (ie: add, update, and view forms)
* `civiawards.php` implements …
> RSE-956: Define award activity types

- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
When creating a new Review Panel, the delete button is visible inside the Review Panel Popup, which is wrong, as it should only appear when editing an existing review panel. This PR fixes this bug.
**Create Mode**
**Edit Mode**
**Create Mode**
**Edit Mode**
1. Inside `review-panels/review-panels.directive.js`, added a new function `prepareButtonsForReviewPanelPopup`, which adds the Delete button only if the Award Review panel id is present(which means an existing review panel).
```javascript
if ($scope.currentReviewPanel.id) {
buttons.push({
text: ts('Delete'),
icons: { primary: 'fa-times' },
class: 'civiawards__award__review-panel-form__delete',
click: function () {
$scope.$apply(function () {
handleDeleteReviewPanel($scope.currentReviewPanel);
});
}
});
}
```
> RSE-1052: Hide delete button when creating new panel

- CRM/CiviAwards/BAO/AwardReviewPanel.php
- tests/phpunit/CRM/CiviAwards/BAO/AwardReviewPanelTest.php
When creating a panel, the Award Manager needs to be able to specify whether a review panel can change the 'status' of an applicant and if so to which status they can change to. This PR adds two extra fields to the list of parameters accepted by the Award Panel BAO when creating an Award Panel to make this possible.
- There are no parameters to support the Award Manager to be able to specify whether a review panel can change the 'status' of an application or not.
Two parameters fields that can be sent from the AwardPanel create API were added to support this functionality: 
- is_application_status_restricted:  _Boolean_
- restricted_application_status:  _Array of status Id's_
> ACU-67: Add Extra Fields To Award Panel Parameters To Support Application Status Restriction

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR displays a warning message when trying to view, create, or edit a review and there are no review fields to display. Previously we were getting a 500 error.
The error happened because we try to get the labels for the custom fields defined as review fields for the review form here:
https://github.com/compucorp/uk.co.compucorp.civiawards/blob/master/CRM/CiviAwards/Form/AwardReview.php#L438-L442
But since no review fields were defined the request looked like this:
```php
'id' => ['IN' => []]
```
which throws an error.
To avoid this we check if whether there are fields defined for the award or not. If there are none, we display the error message, otherwise we display the form as normal:
```php
public function buildQuickForm() {
$fields = CRM_Core_BAO_UFGroup::getFields( …
```
> RSE-955: Display error message when no review fields are defined

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
This PR fixes an issue where applications would not be shown when filtering by "closed" award statuses.
The issue happens because we pass the `Opened` status grouping by default when filtering cases and applications on the dashboard:
https://github.com/compucorp/uk.co.compucorp.civicase/blob/master/ang/civicase/dashboard/directives/dashboard-tab.directive.js#L49
To be able to support the `Closed` status grouping we need to override the `status_id.grouping` parameters so we get all the groupings for the selected statuses and pass them to the `civicase::dashboard-filters::updated` event so it can be passed down to the case panels in turn.
> RSE-898: Allow applications to be filtered by closed statuses.

- config/word_replacement/awards_category.php
This PR updates the word replacement configuration file so it replaces the word "client" for "applicant". We have also made so when we display "a case" we replace it as "an application".
Please refer to https://github.com/compucorp/uk.co.compucorp.civicase/pull/443 to see the technical changes that made this replacement possible.
<table>
<thead>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<th>Case Details People's tab</th>
<td><img src="https://user-images.githubusercontent.com/1642119/79819332-c2b11500-8357-11ea-8b84-3d43a24f4a23.png" /></td>
<td><img src="https://user-images.githubusercontent.com/1642119/79818771-9648c900-8356-11ea-8553-0903dbf0e644.png" /></td>
</tr>
<tr>
<th>Activity Feed</th>
<td><img …
> RSE-1066: Add word replacements for clients

- info.xml
**New Features**
- Allow an Award manager to specify whether a review panel can change the 'status' of an applicant and if so to which status they can change to.
**Improvements**
- Show meaningful error message when trying to add a review and no review fields are available for the award
- Word replacement translation for the word "Client" to "Applicant" in relevant places
**Bug Fixes**
- Fixed issue with status filter is not working for "Closed" award statuses
> CPS-192: Release v1.0.0-beta.2

- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- CRM/CiviAwards/Service/AwardPanelContact.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
- tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
This PR fixes a couple of issues with the AwardReviewPanel.GetContactAccess API.
- Some issues exist
Issues Fixed:
- Return an exception `This contact does not have any access to the panels on this Award` when the API is called and the contact does not have access to any panel on the award rather than return results.
- Add the `status_to_move_to` as part of the return parameters. These are the allowed statuses that the panel contacts can move an application to. An empty array means that the applications cannot be moved by the panel.
- Fix an issue with when merging application tags and statuses for award panels: An empty status setting means that the panel member can filter all statuses, so if there are two panels and one panel setting allows to filter all statuses and the other panel …
> RSE-1083: Fix Issues With AwardPanel GetContactAccess API

- CRM/CiviAwards/Form/AwardCustomField.php
- CRM/CiviAwards/Setup/AddAwardCaseTypeCustomGroupSupport.php
- CRM/CiviAwards/Uninstall/RemoveCustomGroupSupportForAwardType.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1002.php
- templates/CRM/CiviAwards/Form/AwardCustomField.tpl
- xml/Menu/civiawards.xml
This PR adds a form that allows to create/edit custom fields for an award case type and adds the functionality for the creation of custom group sets for award case types.
- These functionalities does not exist.
- The Award Custom Fields form extends the base class form `CRM_Civicase_Form_CaseCategoryTypeCustomField` which allows it to add the custom fields defined for an award for create/edit.
- The `AddAwardCaseTypeCustomGroupSupport` class was created to add the Award Case Type as an entity that can be extended for custom group sets. These makes the Award Case type available as an option on the page for adding Custom group sets.
> RSE-647 - Award Custom Fields Functionality

- .github/workflows/unit-test.yml
- CRM/CiviAwards/Service/AwardPanelContact.php
- ang/test/karma.conf.js
- phpcs-ruleset.xml
- tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
**Scenario:**
- Create a group called group A
- Contact x should be included in group A
- Contact x should be included in a relationship A
- Create an award
- Add a panel to the award
- Include the relationship A that the contact belongs on the Panel
- Exclude group A
- Save award
**Expected behaviour:**
Contact x should be excluded from panel in SSP
**Actual results:**
Contact x is included in panel in SSP
The scenario described in the overview exists.
When a contact belongs to a relationship and belongs to a group that is excluded in a Panel. The contact is not returned as a panel member and is excluded.
- This PR also adds the git workflow for unit tests so that PHP and JS tests are ran when a PR is made.
- A PHP linter error was also fixed by excluding a newly introduced ruleset that …
> RSE-1138: Exclude Groups Should Take Precedence For Panel Contacts Logic

- CRM/CiviAwards/Form/AwardReview.php
- phpcs-ruleset.xml
- templates/CRM/CiviAwards/Form/AwardReview.tpl
- xml/Menu/civiawards.xml
We need to be able to use the Award Review form from within SSP (Currently only accessible within Civicrm) so that a review panel member can add review for an award.
Below are the changes we need to make to the awards review form, both general changes and SSP specific changes:
**SSP Specific changes**
- The review form for SSP must not be themed with shoreditch styles
- A user from SSP can not view the review another panel member left on an Award, i.e user should able to view only own reviews
**General Changes**
- Once a user has reviewed an Award, the review cannot be edited again.
- A user can only leave a single review for an Award.
These changes were not made.
The changes described in the overview section was implemented
| Award Review (Civicrm)  | Award Review (SSP) |
| ------------- …
> RSE-1132: Award Review Form Changes

- CRM/CiviAwards/Form/AwardReview.php
As a part of this PR success and updated  success text value is changed to match designs.
https://projects.invisionapp.com/d/main?origin=v7#/console/19802243/418400657/inspect?scrollOffset=788
The response text has been updated and same text has been consumed by JS at SSP end to show it in the popup. See [FE PR](https://github.com/compucorp/ssp_bootstrap/pull/11).
> RSE-1116: Fix success message text for award submissions

- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
On *Configure Award* page (like `/civicrm/award/a/#/awards/5`) we can create / edit a *Review Panel* - this form is opened in a popup. And there is a **Statuses** field which is always visible regardless of whether related **Panel can change the status of an application?** checkbox is ticked or not.
Actually this checkbox works - it enables / disables the field, but UI doesn’t indicate any difference when the checkbox is ticked and not ticked. It gives an impression to the user that they can select statuses even if the checkbox is not ticked, when in reality they aren’t allowed to do so.
In this PR we are changing the behavior: now select field would be shown / hidden depending on the checkbox.
Just added `ng-show` to the field wrapper.
> RSE-1141: Hide 'Statuses' field In Review Panel popup when related checkbox is unticked

- CRM/CiviAwards/Form/AwardReview.php
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
- ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
There is **Award review** form which displays case tags in the title, but they are being displayed as normal text. This PR makes them displayed like colored badges.
*View review* and *Edit review* form popups are affected.
The `CRM_CiviAwards_Form_AwardReview` class was updated to return colored tags:
1. As now we need to store some more data for case tags (not only name) we renamed `getCaseTags()` to `loadCaseTags()`.
2. The `getCaseTags()` method now returns list of tags in desired format: `plain` (plain text - as it previously was) or `badge` (html - colored badges).
3. As case tag data contain background color, but does not contain text color the `getTextColor()` method was added to return suitable text color for given background color.
By default html in popup title looks like plain …
> RSE-841: Display tag colours on award review form header

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
As a part of this PR basic bootstrap classes and HTML is implemented in order to match it closely with the designs. 
Related FE PR [here](https://github.com/compucorp/ssp_bootstrap/pull/10)
* Custom civicrm classes are removed and bootstrap classes are used to achieve out of the box styles.
* Also, replaced core civicrm action buttons HTML with bootstrap action buttons in order to improve UI.
* The UI mentioned in the after screenshot can be achieved by some extra css overrides done for civicrm in `ssp_bootstrap` [theme here](https://github.com/compucorp/ssp_bootstrap/pull/10).
This HTML contains dummy data for form prefix field. This is done in order to assist BE with development. So, they just need to extract the value from the DB and update it in the HTML template.
In [this …
> RSE-1115: HTML format and class tweaks to achieve design layout

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
- xml/Menu/civiawards.xml
This PR makes some changes to the Award review form for SSP.
The following changes are made:
- Changed the award review form url to use `civicrm/ssp/awardreview`
- Changed permission used by above URL to `CiviAwards: Access awards panel portal`
- Check that logged in contact belongs to a panel on the Award before being able to add a review.
- Fetch form prefix fields to be displayed on the award form fields.
- These changes were not yet done.
- These changes were implemented.
When User tries to add a review for an award he is not panel member of.
> RSE-1172: Award Review Form Changes for SSP

- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- CRM/CiviAwards/Test/Fabricator/Case.php
- CRM/CiviAwards/Test/Fabricator/CaseType.php
- api/v3/AwardReviewPanel.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
The AwardReveiewPanel.getContactAccess API currently returns the application case tags and statuses that a contact has access to based on the panels the contact belongs to for the Award. This API also returns the statuses that the contact is able to move the applications to and if the data should be anonymised or not.
However it is not enough to determine the statuses that the contact is able to move the applications to from this `AwardReveiewPanel.getContactAccess` API because these can change based on the particular application under consideration.
Therefore this PR introduces a new `AwardReveiewPanel.getReviewAcess` API which accepts the Application ID as one of its parameters and will return the statuses that the contact can move this application to and if the application should be …
> RSE-1139: Add AwardReveiewPanel.getReviewAcess API

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR makes some changes to the Award Review form.
- Civicrm Admin/Award Manager can submit one review per application
- Civicrm Admin/Award Manager can not edit a review once submitted. 
- Civicrm Admin/Award Manager can submit multiple reviews per application
- Civicrm Admin/Award Manager can edit a review after it has been submitted.
> RSE-1205: Award Review Form Changes

- CRM/CiviAwards/Helper/CaseTypeCategory.php
- CRM/CiviAwards/Service/ApplicantManagementMenu.php
- CRM/CiviAwards/Service/ApplicantManagementUtils.php
- CRM/CiviAwards/Setup/CreateApplicantManagementOption.php
- CRM/CiviAwards/Setup/CreateAwardsMenus.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1002.php
This PR depends on https://github.com/compucorp/uk.co.compucorp.civicase/pull/515, The Applicant Management option value which is an option value of the Case Category Instance type option group was added in this PR. Also the menu class for the Applicant management Instance was added.
- The Applicant management Menu class and option value was not added.
- The Applicant management Menu class and option value was added.
- As explained in https://github.com/compucorp/uk.co.compucorp.civicase/pull/515, each Case category instance will have it's own menu class which will be responsible for creating menu Items for a case category belonging to a case category instance. The `ApplicantManagementMenu` class was added to create/update/delete menu items for case categories for this instance. The class …
> RSE-1197: Add Applicant Management Instance Menu Class and Option Value

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
As a part of this PR, text and label changes are done on the awards pages
* Change text in the `AwardReview.php` to match the design - https://projects.invisionapp.com/d/main#/console/19802243/418400657/preview
* Change the headline for SSP pages to use case contact name from source contact name.
* Change error message text in `AwardReview.php` as per the implementation.
> RSE-1219: Text changes on the SSP awards form pages

- .github/workflows/unit-test.yml
When working on Tasks that require same Epic branches on CiviCase and CiviAwards that involves the introduction of some new functionality in CiviCase that CiviAwards depend on, when creating a PR with the Awards tech task branch to the Epic branch and in the process of enabling CiviAwards in the Unit test workflow, the installation process may fail due to the fact that it is the master branch of Civicase that is installed and not the Epic branch that contains the code needed for the Awards installation to proceed smoothly
The github workflow for unit tests is updated such that when installing the Civicase extension, which is the main dependency for CiviAwards, the source branch for the CiviAwards PR is first checked to see if that branch exists in CiviCase repo, if it does, we switch to …
> RSE-1222: Improve GitHub Workflow Action Regarding Extensions that CiviAward Depends On

- CRM/CiviAwards/Helper/CaseTypeCategory.php
- CRM/CiviAwards/Setup/CreateAwardTypeOptionGroup.php
- CRM/CiviAwards/Test/Fabricator/CaseCategory.php
- api/v3/AwardDetail.php
- tests/phpunit/Api/v3/AwardDetailTest.php
This PR adds an API that will return the case categories that are of the Applicant Management Category Instance.
- This API is not present
The AwardDetail.getInstanceCategories is added
```php
Sample Request and Response
civicrm_api3('AwardDetail', 'getinstancecategories');
{
"is_error": 0,
"version": 3,
"count": 2,
"values": {
"2": "Awards",
"3": "Awards Project"
}
}
```
> RSE-1199: Add AwardDetail.getInstanceCategories API

- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
Currently the operator between the case status and the case tags field when configuring a panel is the `OR` operator, i.e the panel member can view an application in a specific status or having a specific tag. However this is not correct as the specification states that the operator should be an `AND`. This PR makes that change.
The operator between the Case Status and Case tags field is an `OR` 
The operator between the Case Status and Case tags field is now an `AND`.
This change however brings some changes to the response of the  AwardReviewPanel.getContactAccess API.
Instead of returning an aggregated value for the application status and application tags for all panels, these values are now returned per panel since the application that a user has access to has to be fetched on a per …
> RSE-1140: Change Operator Between Applicant Status And Tags Field in Review Panel to `AND`

- CRM/CiviAwards/Form/AwardReview.php
This PR fixes issue with SSP Awards Review application page where if the review panel member has direct URL of review application page or view submitted review page they can submit/view reviews for the applications which were in deleted state but we should rather show an error message "You cannot submit review for a deleted application." on add review page and "You cannot view review for a deleted application." on view submitted review page.
Case application is deleted from backend but if review panel member has direct URL they can access and add reviews.
View submitted review page
- Added check for Case application "is_deleted" field for SSP review forms and return error message.
> DRU-190: Show error message for ssp awards review application pages where application is deleted

- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
The applications which do not have any tag attached to them are now visible to review panel users if panel does not contain any tag.
If there is a review panel attached to an award that does not include any tags then the user belonging to that panel did not have visibility of the applications which do not have any tag attached to it.
If there is a review panel attached to an award that does not include any tags then the user belonging to that panel is now able to see all the applications regardless of whether the application contains any tags or not.
The logic that was responsible for checking the tags matching had a glitch in it. The condition was not catering the situation where application has empty tags. So the logic was changed to if there are no tags defined in the review panel then …
> RSE-1248: Fix bug in getreviewaccessapi

- CRM/CiviAwards/Form/AwardReview.php
When a user opens a review in view mode all fields should be disabled as it did not make sense to let the user edit the fields when there is no option for saving the form in view mode
Text and select fields were already disabled but attachment, radio, checkboxes fields were not disabled
No matter what the type of a field is, it will be disabled in view mode
Freeze function was being called for form fields in view mode to disable the form fields which was not supported by radio, checkbox and file fields so in addition to the freeze method the disabled attribute is also added for each form field's attributes list in view mode
> RSE-1226: Disable fields for review in view mode

- CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
- CRM/CiviAwards/Service/ApplicantManagementMenu.php
When a new category of instance type application management is created and the Award manager for that category tries to edit/create an Award, there is a permission error when calling the CaseType.get API.
There is also an issue with the Manage Application menu not being visible for the Award manager for the applicant management case type category. 
The issues described above exists.
- The permission for the CaseType.get API is only is modified for only when the case category is Awards. This logic is changed to check if the instance type for the case type category is of Applicant Management.
- Also the Permissions for AwardDetail.get is adjusted to be consistent with what is currently used for the AwardDetail.create and update API for consistency.
- There is an issue with the Manage …
> RSE-1118: Fix Permission Issues When Administering An Award

- CRM/CiviAwards/Form/AwardReview.php
This PR implements Anonymizing Contact Display name on SSP review case application form and view submitted case application form where if the awards review panel is marked with "Anonymise Contacts for this Panel" we shouldn't show Contact Display name of that case application instead we need to show "Anonymous [Case ID]" as display name to awards review panel member while reviewing that case application.
- Add check for SSP review application form to check if that case application has "Anonymize Application" param to true and if yes return "Anonymous [case-id]" as display name
> RSE-1299: Fix contact display name on SSP review application form to respect anonymization

- CRM/CiviAwards/Form/AwardReview.php
This PR fix issue with SSP Review Application and View submitted application forms where we were showing all Tags related to Civicrm Case entity rather than showing all those tags which are added to specific Case application.
- Added `entity_id` param check to load only tags specific for case application id.
> RSE-1311: Fix SSP review and view applications pages to show correct CaseTags

- .github/workflows/unit-test.yml
- README.md
- ang/civiawards/award-creation/directives/basic-details-form.directive.html
As part of this PR
1. The Award Manager Field has been renamed to Manager in the UI.
2. Added Github Action badges to the readme.md file, so that the status of the tests can be seen in the Repositories home page.
3. Update Civicrm version to 5.28.3 in unit test github action.
> RSE-1393: Change Award Manager field label

- ang/civiawards/award-creation/directives/award-custom-field-sets.directive.js
- ang/test/civiawards/award-creation/directives/award-custom-field-sets.directive.spec.js
This PR fixes an issue that happens when trying to save award types, but there are no custom fields defined.
This is a regression issue introduced by https://github.com/compucorp/uk.co.compucorp.civiawards/pull/130 specifically this commit: https://github.com/compucorp/uk.co.compucorp.civiawards/commit/77b99e2
The problem is that when no custom fields are defined, the award form will wait for the non-existent form to trigger a success message, but this will never happen.
To fix this, we automatically resolve the save process of the award's custom field set directive if there are no custom fields defined.
> CPS-360: Fix save award bug when there are no custom fields defined

- CRM/CiviAwards/Service/ApplicantManagementMenu.php
- CRM/CiviAwards/Setup/AddManageWorkflowMenu.php
- CRM/CiviAwards/Upgrader/Steps/Step1006.php
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
As part of this PR, the Manage Workflows menu has been created for `applicant_management` case type categories.
Menu Items were not present.
Menu Items are created. 
1. In `CRM/CiviAwards/Service/ApplicantManagementMenu.php`, added "Manage <caseTypeCategoryName>" menu item for newly created sites.
3. Added a new upgrader which uses `CRM_CiviAwards_Setup_AddManageWorkflowMenu ` class to create menu for existing sites.
> RSE-1380: Add "Manage Workflows" Menu

- CRM/CiviAwards/Setup/CreateApplicantManagementOption.php
As part of this PR, the instance
This PR modifies the `CreateApplicantManagementOption` setup to update the instance type of the `awards` case type category whether the category has previously been assigned an instance or not.
This is necessary because in compuclient deployed sites, it has a static database used and the award case category option value exists when civicase tries to assign an instance type for the awards category. An error occurs because the upgrader version for comopuclient for awards is at `1001` and upgrader `1002` tries to update the `awards` category instance. This causes a duplicate error when inserting in db. 
```php
(
[callback] => Array
(
[0] => CRM_Core_Error
[1] => exceptionHandler
)
[code] => -5
[message] => DB Error: already exists
[mode] => 16
[debug_info] => …
```
> RSE-44: Set instance value whether category instance exists or not.

- CRM/CiviAwards/Service/ApplicantManagementAwardDetailPostProcessor.php
This PR fixes a bug that occurs when a new applicant management case type is being created and the custom field set related to the award sub type is not updated.
The issue described above exists.
- When a custom field set is created for an award subtype, if there is no case type belonging to that subtype yet, the `extends_entity_column_value` is set to NULL. When a case type is added for that subtype, the `extends_entity_column_value` is supposed to be updated with the Case type ID. However there is a restriction that checks if the `extends_entity_column_value` is empty and does not allow this update. This restriction is not needed and this PR removes it.
> RSE-1457: Fix Issue With Award Instance Custom Field Set Not Being Updated

- ang/civiawards-workflow.ang.php
- ang/civiawards-workflow.js
- ang/civiawards-workflow/duplicate-workflow-applicant-management.service.js
- ang/test/civiawards-workflow/duplicate-workflow-applicant-management.service.spec.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/award-creation/directives/basic-details-form.directive.spec.js
- ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
- ang/test/global.js
- ang/test/karma.conf.js
- ang/test/mocks/data/award-additional-details.data.js
- civiawards.php
Fixed the Duplicate `applicant_management` workflow feature. 
1. Created a new angularjs module `civiawards-workflow`, which is dependent on `workflow`.
2. Added `DuplicateWorkflowApplicantmanagement`, with the logic to duplicate applicant_management workflows.
> RSE-1455: Fix Duplicate Workflow functionality

- info.xml
**Improvements**
* Renamed `Award Type` field to `Award Sub Type`. https://github.com/compucorp/uk.co.compucorp.civiawards/pull/146
**Bug Fixes**
* Fixed duplicate Awards functionality. https://github.com/compucorp/uk.co.compucorp.civiawards/pull/145
> CPS-386: Release v1.0.0-beta.7

- templates/CRM/CiviAwards/Form/AwardReview.tpl
It was required to make first word only capitalized for the buttons, but css solution we implemented was not working on **View Review** page (like `/civicrm/ssp/awardreview?action=view&id=22&reset=1`). Reason - the button markup differs from other civicrm buttons. This PR fixes the issue.
We used following css code to use sentense case (capitalise first word only) for button labels:
```scss
.btn {
text-transform: lowercase;
span::first-letter,
&::first-letter {
text-transform: uppercase;
}
}
```
It was not working here because the button does not have `<span>` as a wrapper for button text. It still could work if button would not have an icon, but there is an icon in this case (icon is considered to be the first letter).
So to fix the issue we added `<span>` wrapper for consistency with …
> ACU-370: Fix markup of 'Review Submitted' button

- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/award-creation/directives/basic-details-form.directive.html
- ang/civiawards/award-creation/directives/basic-details-form.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/award-creation/directives/basic-details-form.directive.spec.js
- ang/test/mocks/data/award-additional-details.data.js
This PR displays and sends the data for the "Is Template" field that was first added to the "award additional details" entity here:
https://github.com/compucorp/uk.co.compucorp.civiawards/pull/150
The "Is Template?" field is not present.
The `is_template` field is stored in the basic details directive. The award directive takes care of sending this stored value to the API.
> RSE-1387: Display Is Template field

- ang/civiawards/shared/directives/contacts-group-dropdown.directive.js
This PR fixes an issue where the contact groups selection for review panels would only show a limited number of groups.
We decided to fetch all group records instead of using the `getlist` endpoint that works well with autocomplete inputs because of the following reasons:
* The select2 input was triggering multiple requests to the getlist: one to transform the initial values into proper options with labels, every time a new key was stroked with a 300ms delay, and one after selecting an option (for unknown reasons).
* The implementation was too complicated because of the input's behaviour where an included option can be removed if the same excluded option is selected, and vice-versa. This behaviour was not working well with the ajax implementation and making it work was taking longer than …
> RSE-1404: Fix Contact Group limit

- ang/civiawards/award-creation/directives/award.directive.html
- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
This PR fixes an issue where all statuses are displayed when creating or editing review panels. This statuses should only be the ones selected in the "Award Stages" tab.
The list of statuses is now provided by the award directive instead of the review panel directive. The decision for this is that the award directive has the information about the list of statuses belonging to the award type and the review panel did not. Instead of sending the whole award type data, we send the specific list of statuses we want to display.
The award directive creates the list of status options by checking the status names stored in the award type. If no names are stored, all statuses are returned. This mirrors core behaviour.
Some `ts` service references were removed since they are already provided by …
> RSE-1434: Review panel statuses

- .github/workflows/unit-test.yml
Recently, creating a Drupal site with civibuild step with the github unit tests workflow was failing and as a result, unit tests were not being ran. 
The issue described above exists
Because the command to create the drupal site was ran without specifying the drupal version to build the site with i.e `civibuild create drupal-clean --civi-ver 5.28.3 --web-root $GITHUB_WORKSPACE/site`, civibuild will pull from the [Drupal 7.x master](https://github.com/civicrm/civicrm-buildkit/blob/a44e322faf6d3bc21fbc178d44da2fd078e7ae55/app/config/drupal-clean/download.sh#L7) branch.
The Civibuild site creation was [failing](https://github.com/civicrm/civicrm-buildkit/blob/7461255fc26317979c3261e9318d60bbb88bfcd0/src/civibuild.lib.sh#L1051) at the point where a patch for mysql 8 is to be applied for the …
> CPS-397: Fix failing Drupal Build For Unit Test Workflow

- ang/civiawards-workflow/services/applicant-management-workflow.service.js
- ang/test/civiawards-workflow/services/applicant-management-workflow.service.spec.js
The "New Workflow" button, redirects to the new Award page, instead of new Case Type Page.
"New Workflow" button redirected to New Case Type page always.
Added `redirectToWorkflowCreationScreen` function is `ApplicantManagementWorkflow` service, which redirects to the new Award page.
> RSE-1553: Add Create new button

- ang/civiawards-base/services/process-my-awards-filter.service.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
This pr resolves the bug in award instance type filter. Previously there were some award types on an  instance that did not get displayed as a filter in the overview section on the dashboard.
Some of the award types got missed as can be seen in the picture below.
All the available award types are shown to the user.
Some of the records were missing due to the no limit parameter applied to the api call. If no limit is applied then default limit on an api call for civicrm apis is 25. So now a limit parameter with a value of 0 has been attached to the api call which means to fetch all the available records.
> RSE-1566: Add Option Limit Parameter To Award Manager Get Api Call

- CRM/CiviAwards/Hook/BuildForm/AddFinanceManagementField.php
- CRM/CiviAwards/Hook/CaseCategoryFormBase.php
- CRM/CiviAwards/Hook/PostProcess/SaveFinanceManagement.php
- CRM/CiviAwards/Service/FinanceManagementSetting.php
- civiawards.php
- templates/CRM/CiviAwards/Form/FinanceManagement.tpl
- tests/phpunit/CRM/CiviAwards/Hook/PostProcess/SaveFinanceManagementTest.php
- tests/phpunit/CRM/CiviAwards/Service/FinanceManagementSettingServiceTest.php
This PR adds a new checkbox `Enable Finance Management` to the case type category form creation screen. This checkbox however only shows up for Applicant management case type categories. This setting will be used later to determine applicant management case categories that finance payment tabs will be added for.
This functionality was not yet implemented.
- This functionality is implemented and the checkbox field is added to the case type categories form. 
- A new service `CRM_CiviAwards_Service_FinanceManagementSetting` is created to handle interfacing with the storing, deleting and retrieval of this setting.
- The `Enable Finance Management` checkbox form field was added using the buildFormHook (CRM_CiviAwards_Hook_BuildForm_AddFinanceManagementField) and it's processing was handled …
> ACU-441: Implement Enable Finance Management Setting For Applicant Management Categories

- ang/civiawards-workflow/services/applicant-management-workflow.service.js
- ang/test/civiawards-workflow/services/applicant-management-workflow.service.spec.js
As part of this PR, "Edit Workflow" link redirects to create award page for Applicant Management workflows.
1. Added `getEditWorkflowURL` function in `ApplicantManagementWorkflow` service, which returns url for edit award page.
> RSE-1554: Applicant Management edit workflow link

- CRM/CiviAwards/Helper/ApplicantReview.php
- CRM/CiviAwards/Service/AwardProfile.php
- tests/phpunit/CRM/CiviAwards/Service/AwardProfileTest.php
This PR solves the problem that appears while trying to update the Review Fields positions on a given award.
This was caused by a CiviCRM internal problem, that ignores the weight specified on the create/update API call.
The order that we assign to the review field is not persisted correctly:
Te order persists after saving and refreshing:
I deleted the previous workaround for saving the `weight` value. Anyway, it was not working anymore.
The key to solving the error was to add the option `option.autoweight`.
I did not found information about this option in online documentation or forums, I just inspected myself the CiviCRM code and found it.
Since is undocumented, I added a unit test, that will fail if the core developers remove this option.
> RSE-1231: Fix Bug In Review Field Reordering

- CRM/CiviAwards/Helper/CaseTypeCategory.php
This pr fixes the issue with custom fields on an award configuration page. If there were more than 25 case types belonging to current case category instance then an error occurred on custom fields tab due to which users were not able to configure custom fields for an award.
There was an error message on the custom fields tab
The above mentioned issue has been resolved
There was an api call to fetch all the case types that belong to current case category instance in `CRM/CiviAwards/Helper/CaseTypeCategory.php`, the result of this api call was used to determine that if the current award is valid or not. This api call was missing limit parameter which by default is 25 so only first 25 records were being fetched. This pr adds the limit parameters to the api call with a value of 0 which means …
> RSE-1572: Fix Custom Fields Issue On Awards

- CRM/CiviAwards/Hook/PostProcess/EnableBankDetailsFieldSet.php
- CRM/CiviAwards/Setup/AddCurrencyRelatedCustomFields.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1009.php
- civiawards.php
- tests/phpunit/CRM/CiviAwards/Hook/PostProcess/EnableBankDetailsFieldSetTest.php
- tests/phpunit/CRM/CiviAwards/Service/FinanceManagementSettingServiceTest.php
- xml/custom_fields/payment_bank_details_install.xml
This PR adds the `Awards Payment Bank Details` custom field set for a contact. This custom field set is available for all contacts. 
The Custom field set is created disabled but will be enabled when the `Enable Finance Management` checkbox on the instance configuration screen is enabled and saved.
The first time an instance type has `Finance management` checkbox enabled this custom field set is also enabled. The custom field set is not disable if the `Enable Finance Management` is disabled/unchecked. It is  kept enabled.
This custom field set is not added. 
The `Awards Payment Bank Details` custom field set is added on installation of extension and also an upgrader is added to add this field set for existing clients. The logic to also enable this custom field set is added.
Custom Fields …
> ACU-443: Add the Award Payment Bank Details Custom Field Set

- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
- ang/test/civiawards/dashboard/configs/case-type-items.config.spec.js
- ang/test/mocks/configs/awards-case-types.config.js
- ang/test/mocks/data/award.data.js
This PR blocks reviews from being added or updated for disabled applications.
This PR depends on https://github.com/compucorp/uk.co.compucorp.civicase/pull/679
Please look the last part of the civicase PR.
* The "Add Review" and review action buttons are disabled when the case is disabled.
* Unit tests have been fixed as they were failing before. Civicase updated the way mocked case types are added here https://github.com/compucorp/uk.co.compucorp.civicase/pull/671/files#diff-6549489c078a5b7f418956858cebef0412da1eafa451159dd8e15c4e875db017R415-R421 because the way we were adding data was not consistent. We were passing arrays when we needed to be passing objects. To avoid having inconsistent behaviour only a single case type data object is accepted so we use `_.each` to pass all award …
> RSE-1597: Block reviews for disabled applications

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/civiawards/dashboard/directives/more-filters-popup.html
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
This PR adds a a "show disabled awards" filter. The filter will show awards, applications, and activities that would normally be hidden because they belong to a disabled award.
⚠️ Important: This PR implements the work done in https://github.com/compucorp/uk.co.compucorp.civiawards/pull/75 which had to be closed until a solution for disabled cases would be taken. 
This PR is also related to https://github.com/compucorp/uk.co.compucorp.civicase/pull/675
the filter doesn't exist.
both applications shown here belong to disabled awards
We use the `civicase-checkbox` directive introduced in https://github.com/compucorp/uk.co.compucorp.civicase/pull/675
Some of the changes introduced in https://github.com/compucorp/uk.co.compucorp.civiawards/pull/75  were not implemented in this PR because they …
> RSE-1034: Add filter to display disabled awards and applications

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/civiawards/dashboard/directives/more-filters-popup.html
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
This PR fixes the notifications for the award filters on the dashboard. The notification red mark would stay on as soon as the filter's value changed and would not be removed, as per its normal behaviour, after reverting back the form to its original state.
It also updates the label for the disabled awards filter. The reason for the change is to make it explicit that only disabled awards and applications will be displayed instead of giving the impression of showing both enabled and disabled awards and applications.
This PR is related to https://github.com/compucorp/uk.co.compucorp.civicase/pull/687
* We updated the `isNotificationVisible` function in `more-filters-dashboard-action-button.controller.js ` so it includes the disabled award filter in the check.
* The filter was renamed to …
> RSE-1627: Fix award filter notifications

- ang/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.js
- ang/civiawards/dashboard/directives/more-filters-popup.html
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
- ang/test/civiawards/dashboard/configs/case-type-items.config.spec.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
- ang/test/mocks/configs/awards-case-types.config.js
- ang/test/mocks/data/award.data.js
This PR has all the changes needed to show disabled applications. 
This PR is related to https://github.com/compucorp/uk.co.compucorp.civicase/pull/681
* RSE-1597: Block reviews for disabled applications #172
* RSE-1034: Add filter to display disabled awards and applications #169
* RSE-1627: Fix award filter notifications #178
> RSE-881: Show disabled applications

- CRM/CiviAwards/Api/Wrapper/AwardDetailExtraFields.php
- CRM/CiviAwards/BAO/AwardDetail.php
- CRM/CiviAwards/Service/AwardImport.php
- api/v3/AwardImport.php
- tests/phpunit/CRM/CiviAwards/Service/AwardImportTest.php
This PR adds the functionality of mass-importing Awards, using the [CSV importer extension](https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport) and a new "helper" entity named "AwardImport".
**UPDATE**
It was added improvements on the error handling, for the situations in which some of these fields have an empty value: Award Title, Award Start Date, Award Subtype, Award Manager.
More explanation about these changes on the `Technical Details` part of this PR.
Before there was not possible to import the Awards using the mentioned extension, because it has some related entities that couldn't be imported at the same time. 
The related entities are `AwardDetails`, `AwardManager`, `AwardReviewPanel`, and some other.
Now, going to the CSV Importer extension ( Administer > API csv import …
> CPS-411: Import awards using CSV importer extension

- CRM/CiviAwards/Upgrader/Steps/Step1007.php
- CRM/CiviAwards/Upgrader/Steps/Step1008.php
This pr fixes the error which occurred during deployment due to the fact that some upgraders were modifying the tables but not applying the change to the log table.
Running this upgraders resulted in an error that halted the whole deployment process.
The code for syncing the log tables with new changes have been added to the upgraders.
`Step1007.php` and `Step1007.php` has been updated with the code for syncing the log tables.
> CPS-423: Sync Log Tables With Actual Tables While Running Upgraders

- CRM/CiviAwards/Form/AwardPayment.php
- templates/CRM/CiviAwards/Form/AwardPayment.tpl
- xml/Menu/civiawards.xml
This PR adds the Award Finance Payments form
The Awards Finance Payment Form was not present
The Awards Finance Payment Form was was added.
The Award Payment Form class was added with functionality for creating, viewing and editing an award payment. 
- There will be subsequent PR's to add the functionality for deleting an Award Payment and also to add logic around who can create, view or edit an Award payment and what fields can be edited.
- Basic unit tests will be added in subsequent PR's.
- There form still needs to be styled as some buttons are not properly styled and the form fields are not well aligned but will leave that to FE to style according to spec.
> ACU-441: Add Award Payments Form

- ang/civiawards-workflow/services/applicant-management-workflow.service.js
- ang/civiawards/app.routes.js
- ang/civiawards/award-creation/directives/award.directive.html
- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
- ang/civiawards/dashboard/directives/edit-award-button.controller.js
- ang/test/civiawards-workflow/services/applicant-management-workflow.service.spec.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/dashboard/configs/case-type-items.config.spec.js
- ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
Previously, when pressing the "Save and Done" or "Cancel" button from Award Create/Edit screen, browser always redirected to Dashboard. Now, the redirection happens to Dashboard if Create/Edit Award was clicked from Dashboard. Otherwise the browser redirects to the Manage Awards screen.
In `ang/civiawards/app.routes.js`, added a new route parameter called `redirectTo`. 
When coming from Dashboard page, value of this Parameter is `Dashboard`, and when coming from Manage Awards page, the values is `workflow`. Based on this property, the redirection url is changed.
> RSE-1295: Fix Create/Edit Award Redirection

- CRM/CiviAwards/Service/ApplicantManagementCustomGroupPostProcessor.php
- tests/phpunit/CRM/CiviAwards/Service/ApplicantManagementCustomGroupPostProcessorTest.php
This pr fixes the bug which was causing the awards custom field to leak into other case type category instances.
There were two causes for this bug one was when creating a custom field set for award sub types that do not have any case type associated to them yet the custom field set used to leak into other case category instances and secondly when selecting `any` from the sub type list while creating custom field set there was a glitch in the code due to which the custom field set was not attached to any award.
Above mentioned both the problems are fixed.
`saveCustomGroupForCaseCategory` function in file `CRM/CiviAwards/Service/ApplicantManagementCustomGroupPostProcessor.php` has been modified in such a way to use 0 as the default value for case types if there are no linked awards to the …
> RSE-1620: Fix Award Custom Fields Leakage Bug

- CRM/CiviAwards/Form/AwardPayment.php
- CRM/CiviAwards/Hook/BuildForm/SetCustomGroupSubTypeValues.php
- js/award-payment-form.js
- templates/CRM/CiviAwards/Form/AwardPayment.tpl
- tests/phpunit/CRM/CiviAwards/Form/AwardPaymentTest.php
- tests/phpunit/CRM/CiviAwards/Helper/SessionTrait.php
- xml/Menu/civiawards.xml
This PR adds some business logic to the Awards Payments form. It adds logic that determines when a field is editable and who can edit it and also defines permissions for when an awards payment form can be deleted and who can delete. 
The business logic for editing/viewing/deleting an awards payment form was not present.
**Edit Awards Payment FOrmBusiness Logic**
- If the status of the payment is in: "Exported, Paid, Failed" then the following fields are not editable by the user and are in a disabled state: Payee, Type, Payment amount, Payment currency, Due date, Payee ref. Note that the disabled fields are not validated on the backend, The purpose of the disabled fields just to denote the fact that they shouldn't be changed and they can easily be changed by simply changing the award …
> ACU-489: Award Payments Form Edit/View/Delete Business Logic

- CRM/CiviAwards/Form/AwardPayment.php
- templates/CRM/CiviAwards/Form/AwardPayment.tpl
- xml/custom_fields/payment_information_install.xml
This PR makes some adjustments to the Award payment form.
- The currency type field and the corresponding payment amount fields were aligned so that they are next to each other rather than being on separate lines in the form.
- The Value in Functional Currency Type custom field was renamed to Value in Functional Currency (Just the label) and the Value in Functional Currency field was renamed to Value in Functional Currency Amount (both label and name).
- The ability to configure/add to the currency type option values was also removed for currency type related fields.
- The time stamp for the due date field was also removed so the field is now date only.
These changes were not present.
- These changes are added.
> ACU-502: Award Finance General Edits 

- ang/civiawards-payments-tab/directives/payment-filters.directive.js
- ang/civiawards-payments-tab/directives/payments-table.directive.html
- ang/civiawards-payments-tab/directives/payments-table.directive.js
- ang/test/civiawards-payments-tab/directives/payments-table.directive.spec.js
This PR adds pagination to the list of payments.
This PR depends on https://github.com/compucorp/uk.co.compucorp.civicase/pull/701
All records are displayed in a single page.
We implemented the `civicase-paging` directive on the `payments-table` directive. A `paging` object is defined containing all the information about the current page, the number of records per page, the number of records in total, and if the paging is disabled or not.
We disable paging when loading the payments.
Also, when filtering payments we always go to the first result page, otherwise we risk missing the results.
> ACU-495: Add payments pagination support

- CRM/CiviAwards/Form/AwardPayment.php
This PR removes the ability to configure option type values for currency for the payment currency field.
> ACU-505: Remove Configuration Cog for Payment Currency

- xml/custom_fields/payment_bank_details_install.xml
As part of this PR, the `Awards Payment Bank Details` custom fields has been made Searchable, also fixed naming consistency of the fields.
Added `<is_searchable>1</is_searchable>` for every field.
> ACU-527: Make "Awards Payment Bank Details" custom fields searchable and naming consistency fix

- CRM/CiviAwards/Setup/CreateAwardPaymentActivityTypes.php
This PR fixes the status type for payments. Previously all payments statuses would be "incomplete" when they needed to have different types such as completed, or cancelled.
We added a new `filter` field to the list of activity status types on the `CreateAwardPaymentActivityTypes` setup class. The `filter` field is what is used to determine the type of status and the values accepted are hardcoded integers that can be referenced from constants stored in `CRM_Activity_BAO_Activity`
> ACU-518: Fix payment status types

- ang/civiawards-payments-tab/directives/payments-case-tab-actions.directive.html
- ang/civiawards-payments-tab/directives/payments-case-tab-actions.directive.js
- ang/civiawards-payments-tab/services/awards-payment-activity-status.service.js
- ang/test/civiawards-payments-tab/services/awards-payment-activity-status.service.spec.js
The Edit action button in Payments tab of Case Details was visible for Exported payments, this has been fixed now.
Added `isEditVisible` function to `AwardsPaymentActivityStatus` to fix this.
> ACU-536: Fix Payment Edit action visibility

- CRM/CiviAwards/Form/AwardPayment.php
- js/award-payment-form.js
This PR fixes an issue where fields would be disabled for certain payments and for others the fields would still be disabled when they should be enabled.
There were two issues that prevented fields from being enabled for the right payments:
1. The `crmLoad` load event that we were listening to on `js/award-payment-form.js` was triggering multiple times because this script is loaded every time a new form is opened, but the event listener would trigger even for forms that have already been closed. This would make all the events to act on the current visible form and disable their fields.
2. We were passing the `nonEditableFields` as an array. When adding CiviCRM Settings as objects or array they get extended instead of replaced. As an example, if the first form passed the value `[1,2,3,4]`, …
> ACU-535: Fix Disabled Payment Fields

- CRM/CiviAwards/Form/AwardPayment.php
- ang/civiawards-payments-tab/directives/payments-table.directive.js
- ang/test/civiawards-payments-tab/directives/payments-table.directive.spec.js
- js/award-payment-form.js
This PR fixes an issue where the list of payments would disappear when one of the payments custom data was missing.
Record 158 has no custom data.
Notice the error on the console.
The problem was caused by the `formatPayment` function trying to access the Payment Type's label. If the payment type value was not defined in the payment object it would try to access an undefined object and this would throw an error. To fix this we check if the payment type is defined before assigning the label property otherwise we use an empty string.
> ACU-537: Handle missing payment data

- CRM/CiviAwards/Hook/AclGroup/ActivityTypeCustomGroupAccess.php
- CRM/CiviAwards/Hook/AclGroup/AllowAccessToApplicantReviewGroups.php
- CRM/CiviAwards/Hook/AclGroup/AllowAccessToPaymentGroups.php
- CRM/CiviAwards/Hook/AlterAPIPermissions/Award.php
- CRM/CiviAwards/Setup/CreateApplicantReviewActivityType.php
- CRM/CiviAwards/Setup/CreateAwardPaymentActivityTypes.php
- civiawards.php
- tests/phpunit/CRM/CiviAwards/Hook/AclGroup/AllowAccessToApplicantReviewGroupsTest.php
- tests/phpunit/CRM/CiviAwards/Hook/AclGroup/AllowAccessToPaymentGroupsTest.php
- tests/phpunit/CRM/CiviAwards/Hook/AlterAPIPermissions/AwardTest.php
When a user with the Award Manager role access the award payment listing page or the create/edit form popup, Previously  created award payments are not visible on the listing screen and also on the form, the custom fields belonging to the Award payment information are not visible. 
Payments Listing Screen
Payment Create/Edit Screen
Payments Listing Screen
Payment Create/Edit Screen
- The listing page is created from FE by using the CustomField API to fetch custom fields belonging to the Award Payments group. The permission required to access this API is the `administer CiviCRM and access all custom data` permissions. The Award manager would not have these permissions, so when the custom fields to be accessed is associated with the Payment Information activity type, the newly created …
> ACU-532: Fix Award Manager Permission Issues With Award Payment

- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1007.php
- CRM/CiviAwards/Upgrader/Steps/Step1008.php
This pr adds the code for syncing the log tables with the actual changes at the end of upgrading process so that all the log tables schema remains in sync with the actual tables schema.
This pr changes `CRM/CiviAwards/Upgrader.php` to include the code for syncing the log tables with the actual tables at the end of upgrading process.
> CPS-443: Sync Log Tables In Base Upgrader

- ang/civiawards/award-creation/directives/review-panels/review-panel-popup.html
This PR fixes the label of the Relationship selector on the Awards Create Panel tab from
`Additional Contacts to add to Group` to `Additional Contacts to add to Panel`.
> RSE-1202: Update Panel relationship label

- CRM/CiviAwards/Upgrader/Base.php
- civiawards.civix.php
- phpcs-ruleset.xml
This PR fixes is to updates civix file and an upgrader base class.  The base class and civix file are generated automatically by running `civix generate:upgrader
`
The reason for regenerating the civix file and base upgrader class because CiviCRM changed the way they handle warning for using a deprecated function.  See this [PR ](https://github.com/civicrm/civicrm-core/pull/19256).
The changed will always throw use deprecated warning if the deprecated function is used in anywhere, for example, Drupal module, CiviCRM extension. This would not have an issue we install the extension / module via user interface. However, when we use Drush site-install command to install the Drupal site that ship with a Drupal profile that install the extension when creating a site. 
Any module or extension …
> COMCL-101: Regenerate civix file and Base upgrader class

- .github/workflows/release-pr.yml
Added https://github.com/compucorp/release-pr-action Github Action to Automate Release Pull Request Creation.
The pull request had to be manually created, and the changelog also needed to be manually created by checking difference between last tag and master branch.
Now all of this is automated using Github Actions.
Added `compucorp/release-pr-action@1.0` action.
Also the `jira_ticket_number` and `version_tobe_released` input is taken from user, which is then passed to the action
```
VERSION_NAME: "${{ github.event.inputs.version_to_be_released }}"
FILE_UPDATE_COMMIT_DESC: "${{ github.event.inputs.jira_ticket_number }}: Update info.xml"
RELEASE_PR_TITLE: "${{ github.event.inputs.jira_ticket_number }}: Release v${{ github.event.inputs.version_to_be_released }}"
```
> CPS-464: Add Github Action to Automate Release Pull Request Creation

- CRM/CiviAwards/Setup/UpdateAwardPaymentActivityStatusLabel.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1010.php
As part of this PR Awards Payment Activity Status Labels are updated.
Payment activity title shows activity status type within brackets.
The status type has been removed now from the label.
1. Created `CRM/CiviAwards/Setup/UpdateAwardPaymentActivityStatusLabel.php` to implement this feature.
2. Also added `CRM/CiviAwards/Upgrader/Steps/Step1010.php` upgrader.
> ACU-519: Update Awards Payment Activity Status Labels

- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
This PR fixes Javascript unit tests after they broke from changes done in the Civicase repo.
The review panels directive spec file was failing due to two changes done to the relationship types mock data files in civicase:
* https://github.com/compucorp/uk.co.compucorp.civicase/commit/daf2749c0a32987f85746a803f4bce06c894ef00#diff-90f2ea50f82e507ff64d5ac2572bc9aff3d6e6985e99e1690cc084b6f3065401R68-R86 this changed the mock data from a straight object, to a service that returns copies of the relationship types that can be used in unit tests. We changed `RelationshipTypeData.values` to `RelationshipTypeData.getSequential()`. `getSequential` already returns a copy of the objects so there was no need to clone them.
* https://github.com/compucorp/uk.co.compucorp.civicase/commit/cecd54dff8ac4e24bc …
> CPS-556: Fix unit tests

- CRM/CiviAwards/Service/ApplicantManagementMenu.php
- CRM/CiviAwards/Setup/AddManageWorkflowMenu.php
- CRM/CiviAwards/Upgrader/Steps/Step1011.php
- ang/civiawards/award-creation/directives/award.directive.html
- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
- ang/civiawards/dashboard/directives/edit-award-button.controller.js
- ang/test/civiawards-base/services/is-application-management-screen.factory.spec.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.spec.js
- ang/test/civiawards/dashboard/directives/more-filters-dashboard-action-button.controller.spec.js
- ang/test/civiawards/reviews-tab/configs/add-reviews-tab.config.spec.js
This PR aligns CiviAwards code with the changes introduced on CiviCase, for allowing the usage of long Case Category names.
Also, it fixes a small problem with navigation inside the award creation directives (the cancel button was not working)
PR for CiviCase: https://github.com/compucorp/uk.co.compucorp.civicase/pull/756
The changes here include.
- Modify the menu items for `ApplicantManagementMenu`
- Add upgrader for updating existing menus.
- And the replacements for the frontend, both on code.
> CPS-202: Allow Long Case Category Names For Menus

- ang/civiawards/award-creation/directives/award.directive.js
- ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.js
- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
- ang/civiawards/shared/directives/contacts-group-dropdown.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
While creating awards, the "Add Review Field" popup, only used to show 25 custom fields, now it shows all of them.
Only 25 records were shown.
All records were shown.
Added `options: { limit: 0 }` to the api call in `review-fields-table.directive.js`.
Also replaced all instances of `crmApi` with `civicaseCrmApi`.
> CPS-533: Show all review fields

- CRM/CiviAwards/Helper/CaseTypeCategory.php
- CRM/CiviAwards/Service/ApplicantManagementMenu.php
- CRM/CiviAwards/Setup/CreateAwardsMenus.php
- CRM/CiviAwards/Upgrader/Steps/Step1011.php
This PR updates the menu setup code because of changes done in https://github.com/compucorp/uk.co.compucorp.civicase/pull/760 
This does not change anything visually, only the code is updated so it follows the changes done in https://github.com/compucorp/uk.co.compucorp.civicase/pull/760
`ApplicantManagementMenu`  class  extends `CRM_Civicase_Service_CaseCategoryMenu` and this class was updated to accept the name, label, and singular label to use when creating case category menu items. We now pass the missing arguments.
> RSE-1276: Update menu items setup to use singular labels

- ang/civiawards/award-creation/directives/review-panels/review-panels.directive.js
- ang/test/civiawards/award-creation/directives/review-panels/review-panels.directive.spec.js
- ang/test/mocks/data/review-panels.data.js
This PR solves the problem observed on Award's Review Panels, when one or more of the related contacts groups, tags, or statuses were deleted.
In these cases, the review panel was not visible on the Award review screen.
When the review panel was referencing a deleted contact group, this error was displayed on the frontend code:
preventing the panel rendering. 
The panel is correctly displayed.
- A method for filtering the invalid or obsolete data was added. The method is called when first loaded the Panel, then data is cleaned on the presentation, and also if an edit action occurs, it is saved without this information.
- For doing the unit test, it was needed to make available the method `formatReviewPanelDataForUI`, since is the one in charge of sanitizing the panel, and is called before …
> CPS-559: Handle Missing Data in Review Panel

- ang/civiawards/award-creation/directives/award.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/mocks/data/award.data.js
- package-lock.json
- package.json
Case type configurations was getting wiped when the Award Type is saved. This PR fixes that.
Case Type Configurations were overridden when Award was Saved.
Case Type Configurations are not overridden when Award is Saved.
In `ang/civiawards/award-creation/directives/award.directive.js`, we now keep a backup of the `CaseType` when editing, and assign it back when saving.
> RSESPRT-43: Fix case types being overriddden by award

- CRM/CiviAwards/Helper/CustomGroupPostProcess.php
This PR solves a limitation between the number of Case Types and Custom Groups associations.
Is the implementation for Awards package of the changes made on CiviCase, the please refer to that PR for getting the details: https://github.com/compucorp/uk.co.compucorp.civicase/pull/791
> RSESPRT-45: Fix Limitation Between Custom Groups and Custom Types

- CRM/CiviAwards/Upgrader.php
Some of the recently added upgrader logic was not applied when creating a new fresh site. This PR fixes the same.
Singular Labels were not created.
Singular Labels are created.
> CPS-655: Fix new site deployments

- CRM/CiviAwards/Service/AwardProfile.php
The Review Fields table only shows 25 records, this PR fixes the same.
Only 25 records were shown.
All records are shown.
In `CRM/CiviAwards/Service/AwardProfile.php`, added `'options' => ['limit' => 0],`, so that `AwardDetail` returns all review fields.
> RSESPRT-61: Show all review fields

- README.md
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
As part of this PR, the correct supported CiviCRM and PHP versions has been updated in the ReadMe file.
Also the Unit tests were broken because of https://github.com/compucorp/uk.co.compucorp.civicase/pull/812, so fixed the same.
> CPS-701: Fix Technical Requirements

- .github/workflows/linters.yml
- ang/civiawards-payments-tab/directives/payments-table.directive.html
- package-lock.json
- package.json
This PR adds `value in functional currency` and `value in functional currency amount` to the Awards payment table.
This PR also fix the failing unit test and linters action, one is caused by the node version used by the GitHub action, and it is fixed by instructing the action to read the node version from the .nvmrc file, and the other error is:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/totten/civicrm-scssroot.git
npm ERR! 
npm ERR! fatal: remote error: 
npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
```
This error is fixed by changing the `civicrm-scssroot` git URL to the newly supported [Github URL](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls).
> ACU-775: Add `value in functional currency and amount` to payment table

- CRM/CiviAwards/Form/AwardReview.php
- bin/install-php-linter
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR adds status (Completed/Draft) options field to review applicant and ability to add and update. 
When save a review, the activity status always set to Completed
Use can pick the option between Completed or Draft 
We only fetch the activity status that links contains the link to `Applicant Review` category type. In this stage, if the Draft activity status does not contain `Applicant Review` category type, then the option will not be displayed. 
We also filtered out other activity statuses that may link to Applicant Review category and only display options `Completed `and `Draft  `
> RSE-1774: Add or update review status

- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.html
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
- ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
- ang/test/mocks/data/reviews.data.js
This PR adds activity status in the list on the review tab.
> RSE-1766: Show activity status in the list

- CRM/CiviAwards/Setup/CreateApplicationReviewerRelationship.php
- CRM/CiviAwards/Upgrader.php
- CRM/CiviAwards/Upgrader/Steps/Step1012.php
- ang/civiawards/award-creation/directives/award.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/mocks/data/award.data.js
This PR adds a new relationship type for application reviewers and the new relationship type is assigned as a role to award case types by default.
Awards case types created before now, only have the `Applicant` and `Application manager` roles by default.
New Award case types created after are assigned the `Applicant`, `Application manager` and `Has application reviewed by` roles by default
> RSE-1758: Create and Assign new relationship type Application Reviewer to Award case types

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR adds ability to save draft 
- Save Draft and Save & Continue buttons did not exist. 
- Update action was not allowed on SSP screen. 
- User can only add a new review on SSP screen.
- Save Draft and Save & Continue buttons have been added.
- Update action is allowed when the activity is draft. 
- There is an issue with the margin between Cancel and Save Draft buttons, and this issue will need to be addressed in a separate PR in the _ssp_bootstrap_ theme.
- The status field only requires to display on the Admin screen, since SSP screen and admin screen are sharing the same form, the status is only added to the form when is not loading SSP and application will determine activity status based on the submitted buttons if the submission is from SSP screen.
> RSE-1763: Allow editing review when status is draft

- CRM/CiviAwards/Form/AwardReview.php
- CRM/CiviAwards/Service/AwardApplicationContactAccess.php
- CRM/CiviAwards/Service/AwardPanelContact.php
- api/v3/AwardReviewPanel.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
- tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
This PR allows contact to review award applications they can access based on configured case roles in the award review panel.
`AwardReviewPanel.getcontactaccess` API action only returns access for contact configured by relationship and group in the award panel.
`AwardReviewPanel.getcontactaccess` API action returns access for contact configured by relationship, group and case roles in the award panel.
If a contact has access to review an application via case_role configuration, the specific case ids where the contact has been assigned the role are returned by the `AwardReviewPanel.getcontactaccess` API action.
---
If within the same review panel configuration, a contact has access to review an application by case_roles and relationship/ or group, the contact access would not be limited to …
> RSE-1762: Allow contact to review award applications they can access based on configured role

- CRM/CiviAwards/Upgrader/Steps/Step1012.php
This PR adds an upgrader to assign the Applicant Review category to Activity's draft status and reserve it, so it cannot be deleted.
> RSE-1776: Reserve draft status and assign Applicant Review category

- CRM/CiviAwards/Service/AwardPanelContact.php
- tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
This PR fixes the issue with contact not being granted access to review applications if the award panel is configured with multiple roles.
`AwardReviewPanel.getcontactaccess` API doesn't return access to an application for contact if the award panel is configured with multiple roles.
`AwardReviewPanel.getcontactaccess`API now return access to an application for contact if the award panel is configured with multiple roles.
This issue happened because the multiple case roles are not imploded properly. e.g `['john', 'doe']` is transformed to `'john, doe'` instead of `'john', 'doe'`.
Also, we remove duplicate case_ids for contact.
> RSE-1779: Fix award panel with multiple role configuration

- CRM/CiviAwards/Service/AwardPanelContact.php
- tests/phpunit/CRM/CiviAwards/Service/AwardPanelContactTest.php
In this PR we redefine when a `case role relationship` and `contact relationship` of an award review panel is active; an award review panel is active when: 
> The start date and the end date are null, but the is_active IS TRUE
> 
> OR
> 
> The start date is in the past (<= today) or is null and
> 
> the end date is in the future (> today) or is null
> 
> irrespective of the is_active field.
This would ensure consistency with how an active relationship is defined in  SSP https://github.com/compucorp/ssp_core/blob/master/modules/ssp_core_organisations/includes/misc.inc#L272
> RSE-1762: Update condition of active relationship

- CRM/CiviAwards/Form/AwardReview.php
In this PR we prevent unauthorized users from viewing a review drafted by another user. 
A user can view a draft review they did not create
If a user tries to view a draft review they did not create, they will get an error message.
> RSE-1797: Prevent unauthorized users from viewing draft review

- .github/workflows/unit-test.yml
- CRM/CiviAwards/Form/AwardPayment.php
- CRM/CiviAwards/Test/Fabricator/CaseCategory.php
- tests/phpunit/BaseHeadlessTest.php
- tests/phpunit/CRM/CiviAwards/Form/AwardPaymentTest.php
- tests/phpunit/CRM/CiviAwards/Service/AwardApplicationContactAccessTest.php
Upon changing the test container to PHP8.0, the most prominent errors were caused by the version of PHPUnit used, some of the depreciation errors are:
ReflectionType::__toString() is deprecated in PHP 7.4
ReflectionType::toArray() is deprecated in PHP 7.4
Resolving this would require using PHPUnit 8.2.3 and above, but only PHPUnit 4,5 and 6 are supported by CiviCRM as of now https://docs.civicrm.org/dev/en/latest/testing/phpunit/
https://github.com/sebastianbergmann/phpunit/issues/3728.
Since the version of PHPUnit can't be updated we suppress the errors by decorating the getMockBuilder function to ignore all E_DEPRECATED errors.
> MAE-893: Use PHP8.0 container in Test workflow

- CRM/CiviAwards/Upgrader.php
During the CiviCRM Upgrade task either from the UI or when the command `drush cvupdb` is executed, the task fails with the following error:
unable to call callback ["CRM_CiviAwards_Upgrader”, "syncLogTables"]
This error happens because the `syncLogTables` method was invoked statically even though it was not declared as a static method.
We fix this issue in this PR by changing the function to a static method.
> MAE-903: Allow sync function to be called from a static context

- CRM/CiviAwards/Service/AwardCaseFilterPreProcess.php
At times an Award page doesn't load, this was caused by the use of an undefined constant as a string, and this is no longer supported in PHP 8.0.
> MAE-969: Fix award page not loading

- ang/civiawards-workflow/filters/directives/workflow-list-filter-subtype.html
Fix the Typo from ‘Award Sybtypes’ to ‘Award Subtypes' on the Manage Awards types page.
(URL: [your site]/civicrm/workflow/a?case_type_category=2&p=al#/list”
> CIVIPLUS-1144: Fix typo in civiawards from ‘Award Sybtypes’ to ‘Award Subtypes' on the Manage Awards types page

- CRM/CiviAwards/Upgrader.php
Upgrader is not working.
Upgrader is working fine.
The problem happens because of the migration to PHP 8:
from the PHP 8 migration notes: https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.core.other
> The ability to call non-static methods statically has been removed. Thus [is_callable()](https://www.php.net/manual/en/function.is-callable.php) will fail when checking for a non-static method with a classname (must check with an object instance).
When the upgrader for CiviAwards runs, this function https://github.com/civicrm/civicrm-core/blob/5.51/CRM/Queue/Task.php#L94-L96 gets called with parameter `[CRM_CiviAwards_Upgrader, runStepUpgrade]` and since the function runStepUpgrade is not static it will fail.
> COMPCRM-70: Fix running upgraders on PHP 8 sites

- CRM/CiviAwards/Api/Wrapper/AwardDetailExtraFields.php
This PR fixes creating new awards if the site has some award - Case (Awards) - custom groups and using PHP 8.
We cannot create new awards if the site has some award - Case (Awards) - custom groups and using PHP 8.
We can create new awards if the site has some award - Case (Awards) - custom groups and using PHP 8.
We cannot create new awards if the site has some award - Case (Awards) - custom groups.
The following appears in the docker console output:
```
TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in in_array() (line 57 of uk.co.compucorp.civiawards/CRM/CiviAwards/Api/Wrapper/AwardDetailExtraFields.php)
> Which is this line:  
if (!in_array('award_manager', $apiRequest['params']['pseudo_fields'])) { <-------
return;
> Call stack:
> …
```
> WHFSPRT-429: Fix new award creation

- CRM/CiviAwards/Api/Wrapper/AwardDetailExtraFields.php
This pull request fixes the issue with the Awards creation process. Previously, when attempting to create new awards, it would display an error popup and fail to create the awards.
https://github.com/compucorp/uk.co.compucorp.civiawards/assets/2689257/28898962-2cea-43b4-90cb-e6567b16fb56
- After upgrading PHP to version 8.0, we are encountering a TypeError when adding Awards Manager fields and profile fields to the API results. Additionally, if there are no 'pseudo_fields' present, it throws an error due to the TypeError.
> RCRM-22: Fix typeerror while awards creation process

- ang/civiawards-base.ang.php
- ang/civiawards.ang.php
- ang/civiawards/award-creation/directives/review-fields/review-field-selection.html
- ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.html
- ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.js
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
- ang/civiawards/shared/constants.js
- ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
- ang/test/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.spec.js
When adding "review" fields to an Award type, the fields that appear are coming from a custom group called "Applicant Review Scoring Fields" that is shipped by default with CiviAwards:
here I've added 3 fields to this custom group:
and here you can see the above fields appear when trying to add review fields to an award type:
Civiawards is hardcoded to only use the above custom group, but sometimes we have clients who have large number of review fields (e.g 200 review) that they use for various workflows and processes, and given each custom field represnts a database column in the parent custom group table, the table size will exceed the limit of MySQL which brings down the site and result in various problems.
Here I am adding the ability to configure new custom groups where the fields of …
> CIWEMB-435: Allow using multiple review custom groups

- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR fix the issue for case type label class on review application pages.
Scope: Point 4 from https://compucorp.atlassian.net/browse/MMB-398
This fix was for this ticket - https://compucorp.atlassian.net/browse/MMB-325 (Passed testing)
- Added `badge` class for case tag label, this will not make any impact on the old SSP pages
> MMB-398: Add bootstrap 5 class for case tags label

- ang/civiawards.ang.php
This pr fixes an issue due to which the button for creating new award was not visible
> COMCL-620: Fix Add Award Button Issue

- CRM/CiviAwards/Form/AwardReview.php
- ang/civiawards/reviews-tab/directives/reviews-case-tab-content.directive.js
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This pr adds support for file type fields in review application forms.
The support did not exist and any files uploaded through application review form were not saved.
Now the files can be added to file type fields while reviewing the application and the uploaded file can be accessed as well through applicant review activity or reviews screen
> THFSPRT-6: Add Support For File Fields In Application Reviews

- CRM/CiviAwards/Form/AwardReview.php
- templates/CRM/CiviAwards/Form/AwardReview.tpl
This PR disables the submit button post-click so that the user is prevented from multiple click/submission as this ends up breaking the form submission.
Also, handle error when a user attempts to submit a review without an activity ID.
**User can click on award submit multiple times**
**User can only click on award submit once**
Drupal white page error is displayed if the user attempts to submit a review without an activity ID
Custom error message is displayed if the user attempts to submit a review without an activity ID
> RSESPRT-246: Prevent user from submitting review multiple times

- CRM/CiviAwards/Event/Listener/AlterCustomGroupPermission.php
- CRM/CiviAwards/Event/Listener/AlterOptionValuePermission.php
- ang/civiawards/award-creation/directives/review-fields/review-field-selection.html
- ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.html
- ang/civiawards/award-creation/directives/review-fields/review-fields-table.directive.js
- ang/test/civiawards/award-creation/directives/award.directive.spec.js
- ang/test/civiawards/award-creation/directives/review-fields/review-fields-table.directive.spec.js
- ang/test/mocks/data/award-additional-details.data.js
- ang/test/mocks/data/review-fields.data.js
- civiawards.php
Allow users with award review permission to access custom groups that are configured to be used as review fields.
> RSESPRT-319: Allow Access To Review Custom Groups For Users With Review permission

- CRM/CiviAwards/Settings.php
- ang/civiawards-base.ang.php
- ang/civiawards-payments-tab.ang.php
Previously all the settings needed for angular pages was being passed as plain array but to be compatible with new civicrm version the settings are being migrated to a settings class which fixes a warning on civicrm status page about unsupported settings.
No such warnings are displayed
> COMCL-953: Move Angular Settings To Settings Class

- ang/civiawards-base/services/applicant-management-workflow.service.js
This PR counters an edge case when a manager for a case type has been soft deleted then the case type page does not show any record at all.
No records are displayed if any of the case type manager has been soft deleted
All records are displayed only the manager column is empty for a case type if the manager's contact record has been soft deleted
> BTHASPRT-47: Fix Award Type Display Table

- ang/civiawards-workflow/filters/directives/workflow-list-filter-subtype.html
- ang/civiawards/dashboard/directives/add-award-dashboard-action-button.controller.js
- ang/civiawards/dashboard/directives/add-award-dashboard-action-button.html
Before this PR In some instances, after creating a new ‘Application Management’ type category, the label is displayed as ‘Award’ instead of the actual category name.
> NEUSPRT-456: Set workflow subtype field label to current instance label
